### ISSUE TITLE
Ionic View - app visible on Android but not iOS (just a blank screen)

### ISSUE THREAD

**Issue by gkimpson** [ionic-team/ionic-view-issues#108]
I am using the current latest version of everything:

Cordova CLI 5.0.0
Ionic CLI Version 1.4.5

When using the Ionic share feature I can view my app when using the Ionic View app on my Android device, but when I attempt this same procedure with Ionic View on an iOS device all I see is a blank screen.

Both apps are visible when running them through an Android emulator or iOS simulator.

Is there any way to debug an app while in Ionic view?

**Comment by DaDanny** [comment]
While this article covers an old version of iOS, it should still work for you:

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
