### ISSUE TITLE
Ionic View: SVG (Material design icons) not showing

### ISSUE THREAD

**Issue by stianlp** [ionic-team/ionic-view-issues#124]
I have a problem with Material design icons not working in Ionic View.

I added this script tag and the icons work perfectly in browser.
href="//cdn.materialdesignicons.com/1.1.70/css/materialdesignicons.min.css

However, the icons don't appear in Ionic View.

**Comment by DaDanny** [comment]
Are you seeing any errors in the console? My guess would be you aren't able to download outside files unless you enable it with a plugin such as cordova-plugin-whitelist. 

I'd recommend including these files locally instead of requiring an outside host.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
