### ISSUE TITLE
Inline video doesn't work in Ionic View

### ISSUE THREAD

**Issue by levymetal** [ionic-team/ionic-view-issues#126]
I'm developing an app and testing it in Ionic view. I need to play inline video in my app, but I can't get it to work. I started a thread on the Ionic forum: http://forum.ionicframework.com/t/inline-video-in-ionic-view/28909

According to Mike, this doesn't work because the app inherits the settings from Ionic view, which doesn't have the correct preferences set to allow inline video playback.

Therefore, I suggest the following preferences to be added to Ionic view config.xml:

```
<preference name="AllowInlineMediaPlayback" value="true" />
<preference name="MediaPlaybackRequiresUserAction" value="false" />
```

These preferences won't have any affect for people who don't want to play inline video, but it'll help people like me who do.

**Comment by petetan** [comment]
+1 I just came across this.

**Comment by beebase** [comment]
+1   Won't play inline with videogular either.

**Comment by tlancina** [comment]
Ah thanks for bringing this up, we can definitely fix this in the next release.

**Comment by beebase** [comment]
That's great news :-)   I'm kinda stuck now with my project.

If there's a relative simple fix / workaround, would it be possible to post it somewhere? I'd be happy to hack my ionic source code until next release comes out.

**Comment by tlancina** [comment]
@beebase no workaround that I'm aware of unfortunately, it'll be fixed once View is compiled with the settings mentioned above.

**Comment by beebase** [comment]
Is this issue already scheduled for a version release? Any build or beta will work for me, since I'm not in production yet. Thanks.

**Comment by AaronChen118** [comment]
I am facing the same problem, is there any workaround?

**Comment by beebase** [comment]
not that I know of...

**Comment by hassankhan** [comment]
Has there been any progress on this? :smile:

**Comment by jesiah-hackinglife** [comment]
+1

**Comment by Wtower** [comment]
+1

**Comment by evhar002** [comment]
+1

**Comment by syavash** [comment]
+1

**Comment by ishanmihir19** [comment]
+1

**Comment by vardas-bill** [comment]
+1 really desperate for this feature :)

**Comment by thelamborghinistory** [comment]
+1. Pretty much a year since issue has been opened, I still have this issue :(

**Comment by ValterSantosMatos** [comment]
+1, still no news?

**Comment by dimitri320** [comment]
+1, still nothing?

**Comment by Mxrck** [comment]
Same issue, but adding "playsinline" it works

`
<video autoplay muted loop webkit-playsinline playsinline>
    <source src="..." type="video/mp4">
</video>
`

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
