### ISSUE TITLE
SpeechRecognition(); API not working in Ionic View

### ISSUE THREAD

**Issue by Torquin** [ionic-team/ionic-view-issues#131]
Hi guys, 

Using crosswalk for SpeechRecognition, all's fine when doing "ionic run android" and even on desktop app, but no go when testing with Ionic View. The app works fine until getting to speechrecognition :(

Please help ! 

And a big cheers for the work done !! :)

**Comment by ykpramodh** [comment]
Which plugin are you using for SpeechRecognition?

**Comment by Torquin** [comment]
I'm using the Web Speech API : https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
