### ISSUE TITLE
HELP! Ionic App Build in VS 2013 does not work in Ionic View

### ISSUE THREAD

**Issue by TASimpson** [ionic-team/ionic-view-issues#133]
I built an app in VS 2013 and everything seems to be going great! All the ionic commands work properly and I can debug and change the look of my app with no problems. However, I wanted to have others look at what I have done and once I choose to View App on Ionic View , a blank screen is all I see.

Ionic serve works great locally and I can work through my app just as intended! So why is it that I cannot see my app on my phone via Ionic View?

***_OTHER THINGS I'VE TRIED**_**

I moved a lot of the code around and I can see the "home page".  HOWEVER, NOTHING WORKS functionality wise.

You can see that with the browser, even my photo shows up. But I don't get the same thing in the mobile app that I uploaded to Ionic View. HELP PLEASE!!

I have also deleted, cleared synced multiple times, cleared app data many times, restarted the ionic app...

With doing the above: 

 I see this in the browser and everything works!!!

![image](https://cloud.githubusercontent.com/assets/11613404/10345591/6a5e6f9c-6cf0-11e5-87a0-1ca4eab8c7cd.png)

This is what I see in the Ionic app and nothing works :( 

![image](https://cloud.githubusercontent.com/assets/11613404/10345603/8181e6fe-6cf0-11e5-9dcc-a1f50be64876.png)

Thanks for the help!!!

**Comment by IndyJones72** [comment]
Having a similar issue.  Everything in IONIC SERVE works fine, but when downloading and viewing via IONIC VIEW, it never goes to the login page at all.

**Comment by IndyJones72** [comment]
Ok, maybe this is an issue?  The red indicates a problem correct?  So if that's not downloading/installing, could that be an issue?

![ionicdeploy_issue](https://cloud.githubusercontent.com/assets/15037797/10375757/3e305e52-6dc8-11e5-8523-c0cf70de7cef.PNG)

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
