### ISSUE TITLE
cordova.plugins  is undefined

### ISSUE THREAD

**Issue by anshulbajpai** [ionic-team/ionic-view-issues#134]
My ionic app is using one of the ionic view supported plugin. It works fine when installed directly on android device. 
But when I try to use the app via ionic view on my android, I found out that cordova.plugins is not defined. 
I am not sure what could be the cause of it.
Any help appreciated.

**Comment by ahmedhasanmotiwala** [comment]
http://docs.ionic.io/v1.0/docs/view-usage , check this. :)

**Comment by anshulbajpai** [comment]
I know this. And I've already mentioned that I'm using one of the supported
plugin.

**Comment by DaDanny** [comment]
Have you tried removing the platform and re-adding it? This should force it to re-download and install all the plugins you have listed in your fetch.json file (which for me is found under the plugins folder).

**Comment by anshulbajpai** [comment]
Yea I did that as well.

**Comment by simplesmiler** [comment]
@anshulbajpai can you try https://github.com/driftyco/ionic-view-issues/issues/138#issuecomment-152530372?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
