### ISSUE TITLE
window.cordova undefined on ionicPlatform.ready

### ISSUE THREAD

**Issue by kjellivar** [ionic-team/ionic-view-issues#138]
I have some issues with swipe to go back in Ionic View. I therefore made a really simple Test App to see if it was something in my app causing the issues. But swipe to go back doesn't work there either:

http://codepen.io/teamenonic/pen/dYKPMO

After some testing, I noticed that window.cordova is undefined when $ionicPlatform.ready gets called. I know that the swipe to go back functionality gets disabled when cordova is not present. Can it be that cordova is initialized too late in Ionic View?

Might be related to #134

**Comment by simplesmiler** [comment]
Some insight from https://github.com/driftyco/ionic-view-issues/issues/86#issuecomment-99096792:
> Cordova is injected into the web view after the page has loaded, meaning Ionic will run before Cordova is defined.

The workaround I'm using is described by @tlancina in https://github.com/driftyco/ionic-view-issues/issues/52#issuecomment-99250866:
> So if you guys aren't adverse to a small hack, adding `<script>window.phonegap = {}</script>` to your `<head>` before Ionic loads should force it to wait for the `deviceready` event without stepping on Cordova's toes once it does load. Much simpler than writing $timeout everywhere.

I doubt it will be fixed in 1.x branch.

**Comment by kjellivar** [comment]
Thank you, @simplesmiler, that did the trick :)
Man, this was really messing with me.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
