### ISSUE TITLE
Ionic view app does not work on S3 v4.4.2, but will on 5.1.1 - Can we log errors from Ionic View App??

### ISSUE THREAD

**Issue by TASimpson** [ionic-team/ionic-view-issues#139]
After doing ionic upload, users can see the app I have uploaded, however I cannot see it. Is there a way to be able to log errors that occurred in a specific app from Ionic View?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
