### ISSUE TITLE
Orientation Lock not working

### ISSUE THREAD

**Issue by mdridley** [ionic-team/ionic-view-issues#142]
Using config:

```
<preference name="orientation" value="portrait"/>
```

Orientation is not locked. Would be nice to have it lock.

**Comment by HudsonAfonso** [comment]
+1

**Comment by TheCorbin** [comment]
Was this ever fixed?  I'm having this problem with a new project.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
