### ISSUE TITLE
body has class 'platform-browser'

### ISSUE THREAD

**Issue by martinleopold** [ionic-team/ionic-view-issues#143]
Shouldn't this be 'platform-webview' (or something else)?
Certainly not 'platform-browser' considering the documentation:

> platform-browser  Whether the application is running on the Desktop Browser - applied if you are running ionic serve

fyi, the full list of body classes is see in ionic view:
`grade-a platform-browser platform-android platform android4 platform-android4_4 platform-ready`

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
