### ISSUE TITLE
add possible missing instruction step  to  "LOAD YOUR OWN APPS " page

### ISSUE THREAD

**Issue by cliffordfajardo** [ionic-team/ionic-view-issues#145]
For the third step of the "Load your own apps" page:
![ionic-view](https://cloud.githubusercontent.com/assets/6743796/11350664/82c8a20c-91e7-11e5-81c7-b7d16a35b061.png)

I believe first time users of this app would find it helpful to add a comment about changing into your app's directory before doing the  `$ ionic upload`. 
Today, was my first time using Ionic View and touching Ionic in general , and that missing instruction threw me off a bit, but I was able to resolve it within a minute by looking at your docs.

Perhaps for "Third Step" adding  `$ cd myApp && ionic upload`  would suffice?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
