### ISSUE TITLE
Camera plugin + ionic-platform-web-client - doesn't work in Ionic View

### ISSUE THREAD

**Issue by kowalewski** [ionic-team/ionic-view-issues#146]
First of all I have to mention that I have had working demo of camera plugin (on my andorid device as an apk file and in Ionic View as well).

Then I've added support for Ionic Analytics. I've followed this guide: http://docs.ionic.io/docs/analytics-install. Adding ionic-platform-web-client results with commented out cordova.js and replacing it whith ionic.io.bundle.min.js (it should boostrap cordova).

Since then my camera plugin is not working on Ionic View but it is still working when I do: `ionic run android`.

System info:

```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v0.12.0
```

How do I call for Camera?

Camera service:

```
angular.module('starter')
        .factory('Camera', Camera);

        function Camera($q) {
            return {
              getPicture: function(options) {
                var q = $q.defer();

                navigator.camera.getPicture(function(result) {
                  q.resolve(result);
                }, function(err) {
                  q.reject(err);
                }, options);

                return q.promise;
              }
            }
        }
```

Controller:

```
vm.getPhoto = function() {

        $ionicPlatform.ready(function(){
          alert(Camera);
          Camera.getPicture({
            quality: 75,
            targetWidth: 600,
            targetHeight: 600,
            saveToPhotoAlbum: false,
            allowEdit: false
          })
          .then(function(imageURI) {
            vm.reportPhotos.push(imageURI);
          }, function(err) {
            console.err(err);
          });
        });

      };
```

The action is attached by ng-click directive. When I tap the button on Ionic View nothing happens.
Honestly I don't even know how to debug it.

I've did some research and was trying to fix this with: https://github.com/driftyco/ionic-view-issues/issues/52#issuecomment-99250866 but it didn't help.

Will be glad for any kind of hints ;)

**Comment by ykpramodh** [comment]
My comment might not help but it is to express my doubt. 

Ionic upload automatically zips the www folder and uploads it to ionic.io (you can see the zip file getting created and deleted). How does it upload the plugin code which resides in plugins folder parallel to www folder. In that case, how are the plugins working with Ionic View

**Comment by kishaningithub** [comment]
I think the plugins come embedded with ionic view app
Look at http://docs.ionic.io/docs/view-usage for supported plugins. Its interesting to
note camera plugin is supported.

**Comment by aas1226** [comment]
same problem here, the camera plugin was working on ionic view before "ionic-platform-web-client" was added
but work fine when you build the app

**Comment by vishal41190** [comment]
i am facing the same issue. For me its working on ios but not working on android. Have anyone found any work around for now?

**Comment by JamalANasier** [comment]
Hello guys.. this one i got form this link https://blogs.oracle.com/geertjan/entry/angularjs_cordova_camera_application

you can try the codes, its works for me on : 
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

Good luck

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
