### ISSUE TITLE
Plugin requests

### ISSUE THREAD

**Issue by tobiasSchepers** [ionic-team/ionic-view-issues#15]
Once more congratulations on the great app. Would like to sum some of the plugins I would like to see added to the view app the most. Hope in this way the developers can see what plugins are most desired by developers. 
- geolocation
- social sharing
- local storage
- screenshots
- contacts

**Comment by albertpak** [comment]
+1 for geolocation and localstorage

**Comment by matheuscas** [comment]
I'm already testing my apps with local storage working without problems (using this: https://github.com/auth0/angular-storage).

I would like to propose the following plugins:
- Barcode Scanner (http://ngcordova.com/docs/plugins/barcodeScanner/)
- Bluetooth (https://github.com/don/BluetoothSerial)

**Comment by djabif** [comment]
+1 for this issue.
I would like to add the following plugins:

<ul>
<li>Email composer: https://github.com/katzer/cordova-plugin-email-composer.git</li>
<li>Admob: com.google.cordova.admob</li>
<li>App rate: org.pushandplay.cordova.apprate</li>
<li>inAppBrowser: org.apache.cordova.inappbrowser. It already works but it does not have an option to return back to the app.</li>
</ul>

**Comment by tlancina** [comment]
What is local storage? The Cordova WebView supports local storage already.

Geolocation and BarcodeScanner are in there.  @djabif definitely will be getting email composer in there, inAppBrowser might be a little tricky, but I'll take a look.  It seems like a lot of people would like bluetooth as well.

Currently working on getting Android out this week or next, so the next round of plugins will most likely be coming after that.  Thanks for all the suggestions!

**Comment by tlancina** [comment]
Push notifications https://github.com/driftyco/ionic-view-issues/issues/23.

**Comment by tlancina** [comment]
Evothings Bluetooth https://github.com/driftyco/ionic-view-issues/issues/17.

**Comment by tlancina** [comment]
inAppBrowser https://github.com/driftyco/ionic-view-issues/issues/19.

**Comment by lorneb** [comment]
Does local storage mean that PouchDB should just work, or is something else needed ?
Currently it's seems PouchDB with local storage is not working in my app.  Not sure how to debug any further,  works in browser and Android

**Comment by tlancina** [comment]
@lorneb you should probably be using the SQLite plugin on iOS: http://pouchdb.com/adapters.html#pouchdb_in_the_browser.

**Comment by lorneb** [comment]
Hi @tlancina excellent news,  I'll give it a whirl tomorrow and let you know how it goes. thanks

**Comment by bensperry** [comment]
Closing for now.

**Comment by lorneb** [comment]
Hi @tlancina in IOS 7.1 PouchDB just worked,  for > IOS 8.1 I needed to change over to use the SQLlite adapter.

**Comment by tlancina** [comment]
Hey @bensperry, there are still a few plugins on the roadmap for view, also considering we will most likely continuously be adding them I think this should probably just permanently stay open for the time being

**Comment by LanceEa** [comment]
Any plans to add the File Plugin? :smile:

In my Use Case I'm leveraging ngCordova to call the Camera Plugin which returns the File URI. I then use File plugin to grab the file so I can upload it to the server. It works great on android when I deploy the APK to it. Unfortunately, I only have a Windows PC so not able to throw on iOS device and debug. This is where the awesomeness that which is Ionic View comes in! But, it isn't working and since I can debug my guess is the File plugin (fingers crossed).

**Comment by lorneb** [comment]
Is there a list of all the plugins that have been implemented with Ionic-View?

**Comment by tlancina** [comment]
@LanceEa file plugin is on the road map, but there are a few complications and I want to make sure it's secure

@lorneb you can find the plugin list here: http://docs.ionic.io/tools/viewapp/

**Comment by LanceEa** [comment]
@tlancina - Awesome.Thanks for all the hard work!

**Comment by jspenc72** [comment]
I would like to request all of the plugins supported by ngCordova.

**Comment by pharindoko** [comment]
I like jspenc72`s request :) 
but for login workflows please add as djabif already mentioned the
inAppBrowser (org.apache.cordova.inappbrowser) It already works but it does not have an option to return back to the app.

**Comment by xlozinguez** [comment]
How about https://github.com/driftyco/ionic-plugins-keyboard please? :) :pray:

**Comment by matheuscas** [comment]
I would like to reinforce @djabif request, specially email composer. :D

**Comment by gustafsonk** [comment]
I'd really like to see some form of https://github.com/EddyVerbruggen/Custom-URL-scheme

**Comment by JasonCust** [comment]
Are either the [contacts](http://ngcordova.com/docs/plugins/contacts/) or [calendar](http://ngcordova.com/docs/plugins/calendar/) plugin implementations being tracked?

**Comment by ericterpstra** [comment]
I'd like to request the iBeacon plugin available at https://github.com/petermetz/cordova-plugin-ibeacon

This works great with [Evothings Workbench](http://evothings.com/), but would be nice to have it going on Ionic View as well.

**Comment by apiaget** [comment]
I would also like to request the cordova media plugin (org.apache.cordova.media)

**Comment by dgtman** [comment]
+1 on adding Barcode Scanner (http://ngcordova.com/docs/plugins/barcodeScanner)

All of the ngCordova plugins would be great, but start with barcode scanning ;)

**Comment by triz231** [comment]
I would very much like to see some support for the https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin

**Comment by floomoon** [comment]
+1 for adding iBeacon plugin support (https://github.com/petermetz/cordova-plugin-ibeacon). Well maintaining and works perfectly on my ionic app.

**Comment by Zombitch** [comment]
As floomon suggests, adding iBeacon plugin will be really usefull.

**Comment by ablears** [comment]
Facebook (http://ngcordova.com/docs/plugins/facebook/) and Contacts (http://ngcordova.com/docs/plugins/contacts/) please :)

**Comment by AjinkyaKher** [comment]
InAppBrowser please.. It was extremely painful to figure out why my Facebook integration worked fine on emulator, and not through ionic view. Looking forward to a quick fix of this issue!

**Comment by MichaelJCole** [comment]
I'm trying to figure out if org.apache.cordova.media is supported.

The doc link above: http://docs.ionic.io/tools/viewapp/ is 404

**Comment by simplesmiler** [comment]
@MichaelJCole http://docs.ionic.io/v1.0/docs/view-usage

**Comment by srangaiah** [comment]
BackrounfGeoLocation

**Comment by christophermina** [comment]
+1 for the Media plugin support.

**Comment by tonymccallie** [comment]
+1 for file and media support.. also deploy and push ionic plugins?

**Comment by ashishtilara** [comment]
+1 for push plugin

**Comment by lcgutierrez** [comment]
+1 for In App Browser

**Comment by tlancina** [comment]
[Another one for bluetooth](https://github.com/driftyco/ionic-view-issues/issues/128)

**Comment by tlancina** [comment]
[Couchbase](https://github.com/driftyco/ionic-view-issues/issues/116)

**Comment by tlancina** [comment]
[Scandit Barcode Scanner](https://github.com/driftyco/ionic-view-issues/issues/115)

**Comment by SBejga** [comment]
+1 for File Plugin

**Comment by mikesm** [comment]
ngCordova facebook or OAuth

**Comment by soberstadt** [comment]
[Social Sharing](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin) would be really sweet and don't seem to intensive to add in.

**Comment by quisse** [comment]
+1 for media and media-capture plugin

**Comment by simplesmiler** [comment]
+1 for the File and File Transfer Plugins

**Comment by supys12** [comment]
+1 for contacts plugin supported by ng-cordova

**Comment by rbeers** [comment]
+1 for media plugin

**Comment by ahpiau18** [comment]
+1 for Admob plugin

**Comment by VinceOPS** [comment]
+1 for the NFC plugin :+1:  !

**Comment by billyshena** [comment]
+1 for inAppBrowser

**Comment by blckshrk** [comment]
+1 for the Facebook plugin :+1:

**Comment by kenma9123** [comment]
+1 Local Notification

**Comment by elhamsarikhani** [comment]
+1 InAppBrowser

**Comment by elhamsarikhani** [comment]
@tlancina http://docs.ionic.io/tools/viewapp/ can't be opened
404 Page Not Found.

**Comment by sawo** [comment]
I would recommend the advanced barcode scanner of Scandit. 
https://github.com/Scandit/BarcodeScannerPlugin

**Comment by egm0121** [comment]
+1 for contacts

**Comment by aguerere** [comment]
+1 InAppBrowser

**Comment by marcelor** [comment]
+1 InAppBrowser

**Comment by shamilovtim** [comment]
+ InAppBrowser

**Comment by kishaningithub** [comment]
+1 Contacts Plugin

**Comment by tavikukko** [comment]
+1 InAppBrowser

**Comment by cherniv** [comment]
+111 InAppBrowser

**Comment by kishaningithub** [comment]
Hi ionic people I would like to know ETAs of the plugins that are
Going to be supported by ionic view. I would request 
Contacts and inappbrowser be of priority

**Comment by kishaningithub** [comment]
Just putting all plugins would truly make the entire development cross platform. Especially
when using cloud ide's. Why so stingy on adding plugins?

**Comment by louiswilbrink** [comment]
+1 for Contacts

**Comment by nicopace** [comment]
+1 SMS

**Comment by jouke** [comment]
After quite a search, I finally found this, and the list of currently supported plugins. *sigh*. I wanted to test an app that uses the ImagePicker plugin, so of course I would like to see that one added, but as mentioned before, to us as developers, it would make sense that ngCordova plugins "just work" in Ionic View. Is there a technical limitation why the full range of plugins of ngCordova are not supported by Ionic View?

Also, On the forum, I came across https://forum.ionicframework.com/t/cordova-image-picker-not-working-on-ionic-view/28055 and nobody has referenced this topic, nor the list of officially supported plugins. I will do that now...

**Comment by juniorjp** [comment]
+1 InAppBrowser :/

**Comment by malibagci** [comment]
+1 InAppBrowser

**Comment by jspenc72** [comment]
How about ionic just open source ionic view and let us add the support for the features we want? 
@ionic

**Comment by sydtpt** [comment]
+1 InAppBrowser

**Comment by Tommertom** [comment]
+1 email

**Comment by sikha** [comment]
+1 geolocation and inAppBrowser

**Comment by deinerson1** [comment]
+1 for inAppBrowser

**Comment by smartsdesign** [comment]
+1 for social sharing

**Comment by kent99** [comment]
+1 for geolocation, localstorage and social sharing

**Comment by nowxue** [comment]
+1 for ngCordova plugins, and is there a way we can contribute to this support ? 
I'm most interested in cordova.file-transfer, unless there is a way to do uploads and downloads without needing any plugin.

**Comment by thedub2121** [comment]
+1 for inAppBrowser

**Comment by LintonBlack** [comment]
+1 for inAppBrowser (org.apache.cordova.inappbrowser) It already works but it does not have an option to return back to the app.

**Comment by Winawer** [comment]
+1 for inAppBrowser;  at the moment I have to get our test users to kill the app every time they open an external link when viewing the app through Ionic View.

**Comment by AdrienDC** [comment]
+1 for inAppBrowser, without it, how do I expect to test my app...

**Comment by gustavorocha** [comment]
+1 inAppBrowser

**Comment by RafaelAdao** [comment]
+1 inAppBrowser

**Comment by kishaningithub** [comment]
Why is there no reply for this thread from ionic team?

**Comment by OxiPhobos** [comment]
+1 inAppBrowser

**Comment by micrdy** [comment]
+1 for Social Sharing

**Comment by chris-barnett** [comment]
+1 inAppBrowser, very limited without it

**Comment by poponix** [comment]
+1 inAppBrowser

**Comment by ja1cap** [comment]
+1 for inAppBrowser

**Comment by tlaverdure** [comment]
Screen Orientation please!

**Comment by tlancina** [comment]
Hey all, just to let you know we're still alive and hear you! InAppBrowser and the File plugins require a little bit of extra work on our part, but we're looking into it.

With the latest release on iOS we've added a lot more plugins, and an Android update is in the works. You can see the latest list at http://docs.ionic.io/docs/view-usage#section-supported-plugins.

**Comment by mtoo020** [comment]
Thanks Tim et al. for the update and for building such a great tool :)

+1 for cordova.file please :)

**Comment by eard7** [comment]
+1 Facebook Plugin!

**Comment by cballock** [comment]
Hi, guys. Any plans to support ngCordova Beacons in Ionic View? (http://ngcordova.com/docs/plugins/beacon/)

**Comment by paoesco** [comment]
+1 InAppBrowser

**Comment by golear91** [comment]
InAppBrowser!

**Comment by dconversa** [comment]
+1 for cordova file plugin!
thanks

**Comment by bottomup** [comment]
+1 InAppBrowser

**Comment by pocketmax** [comment]
+1 inappbrowser

**Comment by rolandjitsu** [comment]
NFC would be nice 👍

**Comment by Alain1405** [comment]
NFC is much needed!

**Comment by simonjenny** [comment]
+1 inAppBrowser
+1 Cordova File

**Comment by alexbainbridge** [comment]
Another vote for file & file-transfer !

**Comment by paoesco** [comment]
After some development with Ionic View, I would prefer to have file & file-transfer (between InAppBrowser and File) !

Santa Claus, bring me both :-)

**Comment by brenkehoe** [comment]
+1 inAppBrowser

**Comment by RamirezAmayaS** [comment]
+1 inAppBrowser

**Comment by meizon** [comment]
+1 inAppBrowser

**Comment by alexbainbridge** [comment]
I know starting a discussion with like a gazillion people on an issue is not great..... but here goes. Sorry in advance.

In my view Ionic View ALREADY supports InAppBrowser (at least on IOS). I know its not on the list that Ionic team has published as supported..... but it does work....  

As 80% of the requests on this issue are for InAppBrowser, this is something to ponder!

**Comment by RickeyWard** [comment]
inAppBrowser does not appear to work in ionic view on ios
+1 inAppBrowser

**Comment by gurnard123** [comment]
My app relies completely on the Intel Security plugin I get a blank screen when starting the application.
Can you add the Ionic Inel Security plugin please.

http://ionicframework.com/docs/native/intel-security/

**Comment by brettdorrans** [comment]
+1 File and File-Transfer

No word on these for over a year?

**Comment by tonholis** [comment]
+1 inAppBrowser

**Comment by egreer** [comment]
Upgrade Camera 2.4.0. 
It fixes issues with Android camera and API 24.

**Comment by dimanyc** [comment]
+1 for inAppBrowser. Been jumping from one emulator to another to showcase the progress to a client. Very annoying.

**Comment by Julieng50** [comment]
+1 for AdMobPro, asked at the beginning :)

**Comment by Gamaroff** [comment]
Please add Secure Storage. Thank you.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
