### ISSUE TITLE
AndroidManifest.xml: windowSoftInputMode=adjustPan

### ISSUE THREAD

**Issue by tieum** [ionic-team/ionic-view-issues#150]
For some reasons for Android my application needs **windowSoftInputMode=adjustPan** in the **AndroidManifest.xml**
The ionic view app AndroidManifest.xml is stateUnspecified|**adjustResize**, and as a result the behavior when the keyboard opens is not the same with "android run" (or the .apk) and with the view app.
Did I miss a setting somewhere?
Thanks

**Comment by EnlightenedCode** [comment]
I am also experience this issue.  It would be nice to somehow have this adjusted on Ionic View.  It works fine when I do ionic emulate android or ionic run android (using adjustPan)...but not on Ionic View.  I have set my config.xml to have preference <preference name="Fullscreen" value="true" /> as well

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
