### ISSUE TITLE
Unable to delete app from Ionic View App - Samsung S3 android 4.3

### ISSUE THREAD

**Issue by mfrancisc** [ionic-team/ionic-view-issues#152]
Hi,
Like you can see from the screenshot I'am not able to figure out how to delete an app from the Ionic View App.
![screenshot_2016-01-21-23-21-37](https://cloud.githubusercontent.com/assets/10716933/12496702/90bfe508-c097-11e5-8337-a1caa1278573.png)

Thanks for the great work.

**Comment by ivanp81** [comment]
Same problem on Sammsung Galaxy S4 mini with Android 4.2.2

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
