### ISSUE TITLE
Issues with date formatting on viewer - iOS specific

### ISSUE THREAD

**Issue by boaz-chen** [ionic-team/ionic-view-issues#157]
Hey,

I haven't reduced this issue to the minimal app possible, but did manage to isolate the issue by slowly introducing complexity layers to my app, and noticed that when I have date formatting using angular 2 pipes, the iOS viewer fails to render that specific page. In my case it was a details page which I navigated to (which is supposed to add the Back button when navigated to), which contained a list of dates. What I saw was an empty list but sometimes even worse cases where the app was stuck on a completely empty page, without even showing the Back button. Once I removed the formatting from the date, everything worked as expected. The specific pipe that I used on that date field was `date: 'medium'`.

This issue didn't repro on Android.

Thanks,
Boaz

**Comment by tlancina** [comment]
Sounds like https://github.com/angular/angular/issues/3333#issuecomment-219561520, does adding the polyfill fix your issue?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
