### ISSUE TITLE
Img through CSS does not show picture

### ISSUE THREAD

**Issue by Tommertom** [ionic-team/ionic-view-issues#158]
Hi

I tried to show an image through CSS 

Html:
`<img class="navbarlogo logo"/>`

CSS:

```
.logo {
    content: url('img/logo.png');
}
```

This displays the image in the browser (ionic serve), but not in Ionic View.

If I use a regular `<img src="img/logo.png">` the image is shown.

Similar issue if I try to use background-image on a div.

When I try to show the image in both ways, then one is shown, the other isnt. So apparently it is not a file-upload issue?

Would be nice to be able to use CSS for this configuration, as it allows for easy theming for various customers.

Regards

Tom

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID: Ubuntu Description: Ubuntu 14.04.4 LTS 
Node Version: v4.4.0

**Comment by rpayanm** [comment]
Same issue here
```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.16
Node Version: v4.6.2
Xcode version: Not installed
```

A temporary solution is [convert the image to base64](https://www.base64-image.de/), and:
```
.logo {
    content: url('data:image/png;base64,....);
}
```

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
