### ISSUE TITLE
Robot image stretched and buttons hidden

### ISSUE THREAD

**Issue by tiangolo** [ionic-team/ionic-view-issues#159]
I can preview my app in Ionic View in my phone, but one of the people I'm trying to share the app with is having an issue loading the app.

It seems the main Ionic View App robot image is being stretched, making the "canvas" larger than the screen and leaving the buttons below the screen, and as the scroll is disabled, it's impossible to tap the load app button.

There's a video here in the forums showing exactly how the robot stretches: https://forum.ionicframework.com/t/ionic-view-cant-view-demos/43543

Another post in the forums reporting something possibly similar: https://forum.ionicframework.com/t/glitch-in-ionic-view/45105

And the post from my client: https://forum.ionicframework.com/t/android-view-app-skips-preview-screen-so-cant-add-anyapps/47374

I can't reproduce the bug myself, but to get a similar "problem" I can rotate the phone with Ionic View open. The robot image will be centered and the buttons will get below the screen. As the scroll is disabled I won't be able to tap the buttons.

I see there isn't a deterministic way to reproduce the bug (it happens only in some devices). But to allow using the app and not blocking it completely for some users (as currently) I suggest enabling scrolling. At least while the true source of the glitch is found.

**Comment by rapidtechsolutions** [comment]
Same issue here on GS5.

**Comment by tiangolo** [comment]
Thanks for reporting @rapidtechsolutions 

In the forums, they asked "For anyone else experiencing this, if you could post what device you're seeing it on as well as what version of Android that would be helpful in trying to track it down, thanks!". 

So, if you can provide that data it would be very helpful for the Ionic Team.

I'm also trying to get the device info from my client.

**Comment by GerrySeidman** [comment]
Same issue for me.  

My Phone is a: Blu Dash-M
Android Version: 5.1
Kernel Version: 3.10.72 

BUT... I was able to trick it with the following:

(1) Enter AIRPLANE MODE
(2) Start Ionic View App
(2A) [ Receive message that "Unable to connect to Server:  Status Code 0"
(2B) You end up on the CORRECT SCREEN to Preview an App (ie it doesn't flash past this screen as when you have connectivity)
(3) Disable Airplane Mode
(4) Enter the app code and hit go!
(4A) Bummer I got a message "Please enter a valid app id"
   ... I am checking with my colleagues whether the app is in fact up now.. I'm guessing it isn't.

So I am guessing that the Ionic View first screen activity probably has a timing issue where a flag is set with a background network query before the initial screen appears.   By disabling the network that is avoided.

An alternative solution would be a way to get to the select Preview Activity page from the settings menu or (better) from the "My Apps" page.

**Comment by zinifax** [comment]
I started this thread and desperate for a fix. 

Device Samsung SM-N910G
Android Version 5.1.1

I can send the whoa picture if you want its the same.

One interesting thing is that when signing in can trick app sometimes by holding menu button which then gives me the app name screen.

Good Luck

**Comment by tlancina** [comment]
Hey all, very sorry for the late reply! Is this still an issue with the latest version of View for Android?

**Comment by zinifax** [comment]
I think it is resolved.

Christopher Prince
Zinifax®

mobile: +61 419 324 127 
email: chris.prince@zinifax.com 
skype: christopher prince 
   
This mail is confidential and intended only for the stated recipient(s). If it is received in error, please advise us immediately and delete it. Any unauthorised disclosure, use or dissemination, either whole or partial, is prohibited. This email and any attachments are believed to be free of any virus or defect, but it is the responsibility of the recipient to ensure this. Zinifax does not accept responsibility or liability for any loss or damage arising in any way from its receipt or use or for any errors or emissions in its contents.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
