### ISSUE TITLE
"scan a QR code to view that app" not available on iOS

### ISSUE THREAD

**Issue by cklanac** [ionic-team/ionic-view-issues#162]
According to the [docs](http://docs.ionic.io/docs/view-usage)... 'Tapping "Preview a shared app" lets you enter or scan a QR code to view that app'. But that option isn't available. 

I'm using iPhone 6 with iOS 9.3.1. And tried deleting and reinstalling the app. I've included a screen shot of my phone below

![image](https://cloud.githubusercontent.com/assets/1008777/14392285/a3611216-fd8e-11e5-95fc-137f2d9ac2e9.png)

**Comment by zurfluh** [comment]
According to the [change log of the app](https://itunes.apple.com/ch/app/ionic-view/id849930087?mt=8), this feature was removed in the latest version 1.0.6.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
