### ISSUE TITLE
ionicView.leave and ionicView.enter events fire wrongly

### ISSUE THREAD

**Issue by boyfunky** [ionic-team/ionic-view-issues#168]
Short description of the problem:

I have these two events in my controller and they both fire wrongly. my ionicView.leave event fires when i enter the controller and my ionicView.enter event fires upon leaving the controller. Its so weird. Why is this happening? Also, it only gets called when it is $rootScope and not $scope

What behavior are you expecting?

I am expecting both events to fire correctly.
Steps to reproduce:
1. Go to ur controller, add an ionicView.leave and ionicView.enter event
2. Create a function to enter and leave the controller wt the view
3. Try with $scope and $rootScope

> $rootScope.$on('$ionicView.leave', function() {
>     console.log('on the way leaving')
>   })
> 
> $rootScope.$on('$ionicView.beforeEnter', function() {
>     console.log('on the way entering')
>   })

**Comment by tlancina** [comment]
Does this only happen in Ionic View or in the browser as well?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
