### ISSUE TITLE
Ionic View App "View Error Status 404".

### ISSUE THREAD

**Issue by allen8300** [ionic-team/ionic-view-issues#171]
I'm playing with Ionic official sample "cutePuppyPics".

I can upload it successfully, but I can't view it on Ionic View App "View Error Status 404".

I followed all official documents and tried all methods on google but still can't solve it.

So what is my ionic.project should be like? Or where I'm wrong?

Please save my life.

**Comment by Hanslen** [comment]
I have the same problem, have you fixed your problem???

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
