### ISSUE TITLE
Images not appearing on Ionic-view app

### ISSUE THREAD

**Issue by bbearche** [ionic-team/ionic-view-issues#172]
Ive tried everything from changing the path to switching the image to the main /www directory. I just can't seem to get the image to appear in ionic view. Any help would be greatly appreciated, Thanks guys!

```
<div class="img-container" padding>
    <img src="img/12app-logo.png" alt="">
</div>
```

```
.img-container {
  text-align: center;
  padding-top: 40px 0;
}
```

**Comment by bbearche** [comment]
Fixed the issue. Can't have numbers at the start of the image file.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
