### ISSUE TITLE
App doesn't work properly on Ionic view

### ISSUE THREAD

**Issue by FrancescoMussi** [ionic-team/ionic-view-issues#173]
Hello guys.
I just discovered ionic-view and thought it would be perfect to share the app with the team but unfortunately is not working properly. 

I can see the opening page properly, a project list.
But when cliclink on a project it doesn't open it, doesn't get the data.
Also the menu is not working properly, I cannot access the settings page.

Do you know why it is behaving like this?
(the app is working properly if downloaded from Google store)

If you need i can share my app with you.

Thanks.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
