### ISSUE TITLE
ionic view keeps "forgetting" my apps

### ISSUE THREAD

**Issue by Jarrich** [ionic-team/ionic-view-issues#174]
This is a scenario of the problem I'm experiencing with Ionic View on Android. Confirmed on 2 different  Android devices devices.

1) Log in to ionic view
2) Click on Preview app button on the "No apps yet" screen.
3) Enter app ID
4) App gets downloaded from the server and runs properly inside ionic view.
5) Close ionic view
6) Re-open ionic view
7) The previously opened app is visible in the app-list for a few seconds. Then instantly disappears and we're back on the "Woah. No apps yet?" screen. No work-around except re-entering the app id again.
8) Extra consequence: if we deploy a new version of the app, and we go through the same process of previewing the app using the App ID, the newest version of the app won't be downloaded. instead ionic view will use the previously downloaded app data to run the older version. Solution for this is clearing the app data in the settings screen of ionic view.

**Comment by kylelwm** [comment]
I am experiencing similar issues, any updates or fixes for this?

**Comment by cozzbie** [comment]
+1 This is a major problem.

**Comment by newpointmedia** [comment]
+1 This is affecting me today as well for testers on Android device.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
