### ISSUE TITLE
white screen coming after view app. no output

### ISSUE THREAD

**Issue by chiragandroid** [ionic-team/ionic-view-issues#178]
I have installed ionic view on my android mobile with my ionic account. now i "sync latest app" to sync app in ionic, after that i select view app button. that loading app after that white screen and it is not displaying my first screen like (Register,Login) nothing. only white screen for a long time.

Please solve that. 
My app Id: **a76cac1e** if you want to view app.

**Comment by iwok** [comment]
same here.... but my screen is grey ;)
ionic serve is showing everything fine

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
