### ISSUE TITLE
v1.1.0 - ignores cordova.plugins.Keyboard.hideKeyboardAccessoryBar

### ISSUE THREAD

**Issue by chrisedge** [ionic-team/ionic-view-issues#183]
After updating the view app a couple of days ago, I noticed that the keyboard accessory bar no longer shows up no matter if cordova.plugins.Keyboard.hideKeyboardAccessoryBar is set to true or false within $ionicPlatform.ready().

When running ionic emulate ios, changing the value of cordova.plugins.Keyboard.hideKeyboardAccessoryBar does indeed effect a change.

Much of the time not having the keyboard accessory bar isn't a problem. However, for form select fields there is no way to select an item since the "Done" options doesn't show.

I reviewed the issues and didn't see anyone else with this problem, which is troubling.
Here's my ionic info:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
