### ISSUE TITLE
$http not working

### ISSUE THREAD

**Issue by KevinBeckers** [ionic-team/ionic-view-issues#184]
Hi,

My app uses $http to get data from a server.
But in the view app it looks like the requests wont work.

**Comment by bramu** [comment]
This could be issue with proxy setting not sure how to solve this. I am also facing same issue here. Can someone help us?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
