### ISSUE TITLE
Ionic View not updating app

### ISSUE THREAD

**Issue by MrShakes** [ionic-team/ionic-view-issues#185]
App updated time is correct in the view but app itself is the very first uploaded version even after I delete in view and upload new version.
- IOS Ionic view
- Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by TrySpaceCo** [comment]
Did you ever figure this out?

**Comment by MrShakes** [comment]
Delete Ionic View, re-install. Sometimes works.

**Comment by ChadElias** [comment]
+1 I am also having this issue right now with V2 apps, I have just the base project tabs and tried uploading updated string values to the Home.html and it's not updating at all. I have tried all the steps scene here and nothing seems to work.

Have you figured anything out yet?

**Comment by ChadElias** [comment]
@MrShakes @TrySpaceCo  So I figured out what has been happening with why the view app might not be updating. 

When you run "ionic serve" you'll notice that in your terminal you will see the entire build process execute which will update your www folder with your changes. 

So, the steps seem to be to:
ionic serve
ionic upload

If you do it in that order you'll always have your updates in the view app. I always clear the app data before I open the app as well on the phone.

**Comment by MrShakes** [comment]
That's good, I just switched to TestFlight in my case. Will test later.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
