### ISSUE TITLE
Show swipe info

### ISSUE THREAD

**Issue by Cm-8** [ionic-team/ionic-view-issues#186]
the "swipe info overlay" at the start of the app is not show properly on iphone 5s

![file_000](https://cloud.githubusercontent.com/assets/21364091/18544129/9a8a8974-7b33-11e6-92f9-0a123d4cf91f.png)

**Comment by tlancina** [comment]
Hmm, do you mind emailing me the app id this happens on at tim()ionic.io? I
wonder if there is a CSS conflict. It might make more sense to have it be a
native overlay if that's the case so that can't happen...

**Comment by Cm-8** [comment]
it happens with three different app, now i send you the id's.

**Comment by tlancina** [comment]
Thanks, I'll take a look when I get a chance. What version of iOS are you seeing this on?

**Comment by Cm-8** [comment]
i'm try in 8.1.2

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
