### ISSUE TITLE
Ionic 1.x View error on android device: Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by samazary** [ionic-team/ionic-view-issues#189]
I'm getting this error below on an Android Device in Ionic View (works fine with no errors in 1) desktop chrome and 2) an android build on the device):
Uncaught SyntaxError: Unexpected number ionic.bundle.min.js?ionicCachebuster=69501:74

Has anyone else had this? Any ideas how to fix it?

![98cff386-7e34-11e6-8a1c-5262fb990313](https://cloud.githubusercontent.com/assets/17037047/18930603/fda4c654-860b-11e6-9a77-da77373f3c3e.png)

Here is the place in the file ionic.bundle.min.js where the error is occurring:
![2c96b73e-7e36-11e6-8b3a-1cc0b997ba5c](https://cloud.githubusercontent.com/assets/17037047/18930610/038c0866-860c-11e6-933b-069ef982866f.png)

ionic info:
![image](https://cloud.githubusercontent.com/assets/17037047/18930696/7aa5692e-860c-11e6-8388-67ae1b569e11.png)

**Comment by tlancina** [comment]
@samazary are you using Crosswalk? Could it be that there is a polyfill missing or something?

Also, how are you getting an inspector on View?

**Comment by samazary** [comment]
@tlancina nope not using crosswalk and I'm using https://www.genuitec.com/products/gapdebug/ to view inspector/console etc

**Comment by tlancina** [comment]
@samazary hmm I wonder if the cachebuster being appended to asset urls messed something up... Can you see any incorrectly closed quotes or filenames in index.html?

**Comment by samazary** [comment]
@tlancina the index.html file is actually completely empty on the device, is this normal?

![image](https://cloud.githubusercontent.com/assets/17037047/19169908/0d6c91dc-8c62-11e6-9faa-6a3f7afd78c7.png)

**Comment by tlancina** [comment]
@samazary would you mind emailing me the app id at tim ~ ionic.io? If I have time I'll take a look later today

**Comment by samazary** [comment]
hi @tlancina I have emailed you the app id, let me know if you don't have it yet. Did you have any luck investigating this error?

I'm trying to run the app on an Android 7.0 device (not in Ionic View) and I'm getting a similar error to the Ionic view error:
![image](https://cloud.githubusercontent.com/assets/17037047/19252974/a8fd2f9c-8f93-11e6-9b1a-7cddbf61f3aa.png)

**Comment by tlancina** [comment]
@samazary did you have any luck tracking this down? I believe I took a look and there was a different error happening at the time.

**Comment by samazary** [comment]
Apologies for the delay Tim, the issue still remains, I will take another look next week and see if I can see the problem and try to find a solution, I'll report back then but let me know also  if you have any ideas on what I can try to diagnose it?

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
