### ISSUE TITLE
StatusBar doesn't work

### ISSUE THREAD

**Issue by Marcotrombino** [ionic-team/ionic-view-issues#191]
Hi everyone,
I'm having some problems with cordova StatusBar on iOS ionic view app (These problems started since 1.1.1 update, in fact I didn't have problems before it).
I'm trying to interact with StatusBar without results (changing color, hiding etc)
I tried many solutions, but I can't resolve the problem:
- **Attempt to fullScreen and hide StatusBar (Works before 1.1.1 update)**
  <br>The result is a **white bar without text**, so `StatusBar.hide();` doesn't work!

``` js
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.disableScroll(true);
      ionic.Platform.fullScreen();
    }
    if(window.StatusBar) {
      StatusBar.hide();
    }
  });
})
```
- **Attempt to change StatusBar color**
  <br>No results, same default status bar

``` js
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if(window.StatusBar) {
      StatusBar.backgroundColorByHexString('#3153B6');
    }
  });
})
```

I also tried without results :
`cordova plugin add cordova-plugin-statusbar` 
or `cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git` 
<br>In the end I tried to change **config.xml** with 

``` html
<preference name="StatusBarOverlaysWebView" value="true" />
<preference name="StatusBarBackgroundColor" value="#BE1912" />
```

without results.
I can't find a solution!

**Comment by tlancina** [comment]
Hey thanks for the issue, you are not the first to report this but I've been unable to reproduce any problems so far. 

What device and version of iOS are you seeing this on?

**Comment by Marcotrombino** [comment]
Thanks for the reply, I'm on iPhone 5 9.3.2 and iPhone 6S 10.0.2. I've another project on ionic view app with the same problem (and worked perfectly before app update)

**Comment by tlancina** [comment]
Re-opened https://github.com/driftyco/ionic-view-issues/issues/181 as well, I can confirm there is an issue with the statusbar background view not being removed. Possibly from View and the iAB having separate plugin instances?

Will take a look further when I get a chance.

**Comment by 1BJK903** [comment]
I have the same issue here... hope it can be fixed soon.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
