### ISSUE TITLE
Base64 image doesn't show in IonicView (iOS v10.0)

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-view-issues#192]
_From @hothmiles on October 27, 2016 6:38_

Hi 

I have a small issue with Ionic View and the use of the camera with Ionic2, when I upload my app on Ionic View and try to use to picture I just took it works just fine with an Android device but not on iOS. Strangely when I build on my device with Xcode then the picture is rendered perfectly. 

`then((imageData) => {
      this.base64image = "data:image/jpeg;base64," + imageData;`

`<ion-card-content>
      <img [src]="base64image" *ngIf="base64image" />
    </ion-card-content>`

_Copied from original issue: driftyco/ionic#8924_

**Comment by splacentino** [comment]
Same issue for me.

**Comment by mcornillon87** [comment]
Same issue. Building with Xcode didn't work for me...

**Comment by istornz** [comment]
Any fix ? I have this issue too...

**Comment by alexbainbridge** [comment]
I had this problem too

Workaround is to receive from the camera as Camera.DestinationType.FILE_URI . That works while the base64 data version does not (in Ionic View)

Works either way with app directly on device, so is something to do with Ionic View..... perhaps related to all the memory warnings in the camera plugin documentation regarding DATA_URI

**Comment by alexbainbridge** [comment]
One thing the Ionic team could do is make the example code here https://ionicframework.com/docs/v2/native/camera/ be code that uses FILE_URI - so will work immediately on Ionic View. Might save some headaches!

**Comment by alexbainbridge** [comment]
Coming back to this, the original cause may also be something to do with **data:** not being in the content security policy, meaning base64 encoded images won't work for security reasons.....   

Would need to see the Ionic View code to really see if this is likely or not!

**Comment by alexbainbridge** [comment]
OK I have found the solution :)   

Documenting here for clarity 

WORKAROUND 

You can use FILE_URI rather than DATA_URL. 

The "however" is that Ionic View doesn't (currently) support File or File Transfer plugin, so if you do have the image as a file, and want to get it off the device, there are limited options, hence why I guess we are all using DATA_URL in the first place

PROPER SOLUTION
I had two problems with the default setup within Ionic View (was working fine when directly on device)

A) Showing the image on the device screen straight after taking.
Solution is to use DomSanitizer
https://angular.io/docs/ts/latest/api/platform-browser/index/DomSanitizer-class.html

For example

`<img [src]="_DomSanitizationService.bypassSecurityTrustUrl(imageDataURL)" *ngIf="imageDataURL"/>`

Where you have imported it 
`import {DomSanitizer} from '@angular/platform-browser';`

and added to your constructor
`public _DomSanitizationService: DomSanitizer`

That works and addresses the problem first raised by the first on this thread @hothmiles

B) I then had an issue getting the Base64 image OFF the device. This stumped me for a long long long time

Turns out that the camera plugin used on Ionic View is not the same version (or same configuration) as calling the Camera Plugin directly, when app installed directly on device.

I am using a form post http request to get an image off the device...... and the Camera Plugin on Ionic View is inserting newlines into the base 64 data every 74 characters or so, breaking the form post, but the camera on my test devices, when called directly via the Camera Plugin, is not adding these newlines. Due to being Ionic View specific, hard to track down. 

Remove the newlines
`this.imageDataURL = this.imageDataURL.replace(/(\r\n|\n|\r)/gm,"");`

Once removed, voila, works!


Hope the above notes assists someone!

**Comment by adevoid** [comment]
Hey Alex, 

My Base64 image takes forever to appear when running my app with Xcode directly on my device. It wont appear at all if I don't push() it to another page or if I set options like "correctOrientation" to true. I see you said it should work either way with FILE_URI or DATA_URL if it is running directly on the device. I've been trying to figure this out for a while. My code seems pretty straight forward, but I must be missing something.

I posted my code on to the Ionic 2 forums:
https://forum.ionicframework.com/t/cordova-camera-image-incredibly-slow-to-appear-in-view/80509

**Comment by splacentino** [comment]
Still having the issue

**Comment by breault-vincent** [comment]
+1. Also still having issues.

**Comment by Peege151** [comment]
+1

**Comment by Peege151** [comment]
+1

**Comment by Anilinfo2015** [comment]
+1

**Comment by scottmotion** [comment]
I have this working code for viewing the captured image:

typescript file:

  takePicture(){
    let options = {
      targetWidth: 500,
      targetHeight: 500,
      quality: 100,
      allowEdit: true,
      correctOrientation: false,
      saveToPhotoAlbum: true,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    };
    this.camera.getPicture(options).then((imageData) => {
      this.pictureTaken = true;
      // imageData is a base64 encoded string
      this.base64Image = "data:image/jpeg;base64," + imageData;
      let cameraImageSelector = document.getElementById('camera-image');
      cameraImageSelector.setAttribute('src', this.base64Image);
      }, (err) => {
        console.log(err);
    });
  }

html file:

<ion-item *ngIf="!pictureTaken" (click)="takePicture()">
  <img src="{{placeholderImage}}" />
</ion-item>
		
<ion-item (click)="takePicture()">
  <img id="camera-image" />
</ion-item>

**Comment by aspidvip** [comment]
1+

**Comment by aspidvip** [comment]
index.html
```
<div *ngFor="let img of base64Image">
      <img (press)="DelFoto(img)" style="width:100%; height: auto; box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.2), 0 3px 5px 0 rgba(0, 0, 0, 0.19);" [src]="img.src_full"/>
      </div>
```
index.ts
```
      options = {
            quality: 50,
            destinationType: this.camera.DestinationType.DATA_URL,
            sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
            encodingType: this.camera.EncodingType.JPEG,
            mediaType: this.camera.MediaType.PICTURE,
            allowEdit: true,
            targetWidth: 1000,
            targetHeight: 1000,
            correctOrientation: true  //Corrects Android orientation quirks
        }
    
 this.camera.getPicture(options).then((imageData) => {
     //this.base64Image = 'data:image/jpg;base64,' + imageData;
     //alert(imageData);
     this.base64Image.push({
       id: null,
       procent: 0,
       src_full: 'data:image/jpeg;base64,' + imageData
     });
}, (err) => {

});
```
The image does not appear on the screen, white <img> Previously, a few days ago, everything worked

**Comment by Peege151** [comment]
@scottmotion What does your `ionic info` show you?

**Comment by aspidvip** [comment]
Ionic info: (run ionic info from a terminal/cmd prompt and paste output below):
Cordova CLI: 7.0.1
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8
Node Version: v6.10.3

**Comment by scottmotion** [comment]
@Peege151 
global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by Peege151** [comment]
@scottmotion Thanks, your code worked for me... I'm not sure what I had that was different, I will try and find some time to investigate.

**Comment by scottmotion** [comment]
Btw I forgot to add the [hidden] attribute to the camera image ion-item. Do not use ngIf because the element will not be rendered, just hide it.

**Comment by gabriellecozart** [comment]
I fixed this issue (after several painful hours) by using ion-img instead of the regular img. Since I am working with ionic 3, ion-img uses lazy loading which causes many problems trying to scroll through my app. This isn't a permanent solution, but it now works with Ionic View. Will try to test by running it on a connected device to see if regular img works.

**Comment by rodrigo85** [comment]
Hello
@gabriellecozart , I tried the ion-img but it did not display the image when running in the ionicview.

@scottmotion , I also tried your code but it did not display the image when running in the ionicview.

**Comment by gabriellecozart** [comment]
@rodrigo85 Hmm.... I noticed the same thing a few hours ago. I tried running another project the same way and used ion-img instead but it isn't working. I must have added something to the old project that fixed it but thought it was ion-img that fixed it. Funny thing is, regular img still does not work. I will try something things with ionic view to see if it works, but the best thing I can advise you to do is if you have an android phone, plug it in to your computer (make sure developer options are enabled) and then run `ionic platform add android` then `ionic run android -l`. These plugins are not great to test out on ionic view so it's best to test them on physical devices.

**Comment by rodrigo85** [comment]
Thanks @gabriellecozart .

ok, I will accept your sugestion.
Just a question... I already tried to emulate using android studio, but the emulator was so F*$%# slow. Do you have any tip about it. I have 8 GB RAM but it seems I need 16 GB at least.... LOL

**Comment by gabriellecozart** [comment]
Make sure you have HAXM installed. Before the migration to android studio things were even worse with the ADT bundle... HAXM made a big difference but I think it's manual installed with Android Studio now. If you do have it installed and are still noticing issues, make sure you only deploy it to the emulator once and simply refresh on save. You shouldn't have to redeploy it everything (if that's what's happening).

**Comment by webmobiles** [comment]
@aspidvip @scottmotion  I have got this erros in your both codes:

Property 'base64Image' does not exist on type 'PhotoPage'

what is base64Image ?

**Comment by scottmotion** [comment]
Here's a snippet of my latest solution. Take a picture or select from photo gallery, then display bas64 image in the view. Use the original source image (rawImage and imageSrc in this case) for uploading to Firebase. The various elements are hidden/shown based on button clicks. BTW using latest recommended/stable versions of all packages.

html:
>
	<ion-list no-lines *ngIf="!pictureTaken && !pictureChosen">
	  <button ion-button block large icon-end *ngIf="!pictureTaken && !pictureChosen" (click)="takePicture()">
		Take a picture
		<ion-icon name="camera"></ion-icon>
	  </button>
	  <h2 align="center">or</h2>
	  <button ion-button block large icon-end *ngIf="!pictureTaken && !pictureChosen" (click)="openGallery()">
		Choose a photo
		<ion-icon name="images"></ion-icon>
	  </button>
	</ion-list>

    <img id="camera-image" [hidden]="!pictureTaken" />
    <ion-fab bottom right [hidden]="!pictureTaken">
	    <button ion-fab mini color="light"><ion-icon name="arrow-dropleft"></ion-icon></button>
	    <ion-fab-list side="left">
	        <button ion-fab color="light" (click)="takePicture()"><ion-icon name="camera"></ion-icon></button>
	        <button ion-fab color="light" (click)="openGallery()"><ion-icon name="images"></ion-icon></button>
		<button ion-fab color="danger2" (click)="cancelPicture()"><ion-icon name="trash"></ion-icon></button>
	    </ion-fab-list>
    </ion-fab>

    <img id="gallery-image" [hidden]="!pictureChosen" />
    <ion-fab bottom right [hidden]="!pictureChosen">
	    <button ion-fab mini color="light"><ion-icon name="arrow-dropleft"></ion-icon></button>
	    <ion-fab-list side="left">
	        <button ion-fab color="light" (click)="takePicture()"><ion-icon name="camera"></ion-icon></button>
	        <button ion-fab color="light" (click)="openGallery()"><ion-icon name="images"></ion-icon></button>
		<button ion-fab color="danger2" (click)="cancelGallery()"><ion-icon name="trash"></ion-icon></button>
	    </ion-fab-list>
    </ion-fab>

  </ion-item>


typescript:
```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, ViewController} from 'ionic-angular';
import { Camera } from '@ionic-native/camera';

@IonicPage()
@Component({
  selector: 'page-new-project',
  templateUrl: 'new-project.html',
})
export class NewProject {

  public loading: any;
  public base64Image: string;
  public rawImage: string;
  private pictureTaken: boolean;

  public imageSrc: string;
  public imageSrcBase64: string;
  private pictureChosen: boolean;

  constructor(public navCtrl: NavController, public navParams: NavParams, private view: ViewController, private camera: Camera) {

  }

  takePicture() {
    let options = {
      targetWidth: 1000,
      targetHeight: 1000,
      quality: 50,
      allowEdit: true,
      correctOrientation: true,
      saveToPhotoAlbum: false,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    };
    this.camera.getPicture(options).then((imageData) => {
      this.pictureChosen = false;
      this.pictureTaken = true;
      this.rawImage = imageData;
      // imageData is a base64 encoded string
      this.base64Image = "data:image/jpeg;base64," + imageData;
      let cameraImageSelector = document.getElementById('camera-image');
      cameraImageSelector.setAttribute('src', this.base64Image);
      }, (err) => {
        console.log(err);
      });
  }

  cancelPicture() {
    this.pictureTaken = false;
    this.rawImage = null;
    this.base64Image = null;
  }

  openGallery () {
    let options = {
      targetWidth: 1000,
      targetHeight: 1000,
      quality: 50,
      correctOrientation: true,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      destinationType: this.camera.DestinationType.DATA_URL,      
      encodingType: this.camera.EncodingType.JPEG     
    };
    this.camera.getPicture(options)
      .then((imageData) => {
        this.pictureTaken = false;
        this.pictureChosen = true;
        this.imageSrc = imageData;
        this.imageSrcBase64 = "data:image/jpeg;base64," + imageData;
        let galleryImageSelector = document.getElementById('gallery-image');
        galleryImageSelector.setAttribute('src', this.imageSrcBase64);
      }, (err) => {
        console.log(err);
      });   
  }

  cancelGallery() {
    this.pictureChosen = false;
    this.imageSrc = null;
    this.imageSrcBase64 = null;
  }
}
```

**Comment by lianesten** [comment]
I had the same issue on iphone 7 device - ios 10.3 - ionic 2. Now i am using <ion-img> tag instance of <img>. I tested on real devices and work fine both(android/IOS)

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
