### ISSUE TITLE
Statusbar color not changing on Ionic View

### ISSUE THREAD

**Issue by 1BJK903** [ionic-team/ionic-view-issues#193]
Maybe I am doing something wrong, I don't know, but I can't get it working.
  $ionicPlatform.ready(function () {

```
    if (window.cordova && window.cordova.plugins.Keyboard) {

      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

      cordova.plugins.Keyboard.disableScroll(true);
    }
    if (window.StatusBar) {
        StatusBar.backgroundColorByHexString("#FFFFFF");
    }
```

And even changing some preferences in config.xml doesn't work... it just shows the same default color of the status bar. Is there any fix for this?

**Comment by fiznool** [comment]
Same issue with Ionic v2. The following code doesn't have the desired effect.

```
this.platform.ready().then(() => {
  StatusBar.backgroundColorByHexString('#4b3953');
});
```

**Comment by NickPJabico** [comment]
My status bar changes take effect, then reverts back to default color.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
