### ISSUE TITLE
Three finger swipe does not work on Android Nexus (5, 6P)

### ISSUE THREAD

**Issue by graficon** [ionic-team/ionic-view-issues#194]
Hello,

Three finger swipe for feedback does not work on Nexus 5 and 6P (Android).

Works fine on iOS (5s, iPad Mini 4)

Anyone else encountered this issue?

Thanks!

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
