### ISSUE TITLE
cordova-plugin-media not working

### ISSUE THREAD

**Issue by withinsight** [ionic-team/ionic-view-issues#196]
I'm using cordova-plugin-media in an Ionic 2 app, and audio is working in the iOS simulator, and on an iPad Air 2, but not in Ionic View.

I have the native calls wrapped in this conditional, and I'm wondering if this would return false for some reason in Ionic View:

if (this.platform.is('ios') || this.platform.is('android'))

**Comment by withinsight** [comment]
I've confirmed this is not my conditional code, and is in fact an issue with the plugin in Ionic View.

**Comment by withinsight** [comment]
Further follow up here; I noticed from reading this thread (https://github.com/driftyco/ionic-cli/issues/1324) that plugins for View need to be in the config.xml (ours was not). I tested running 'ionic add plugin cordova-plugin-media --save', which adds this line to config.xml:

<plugin name="cordova-plugin-media" spec="~2.4.0" />

and re-submitting to View, but this still has not resolved the issue.

**Comment by withinsight** [comment]
Any way we could bump up getting the media plugin to work in View? Its on the list of approved View plugins, is not currently working, and is impacting client work for me.

**Comment by tlancina** [comment]
Hey @withinsight, sorry you're having issues. What version of View, OS, and device are you using?

**Comment by withinsight** [comment]
Hi @tlancina, thanks for looking into this! 

View 1.1.1
iOS 10.1.1
iPad Air 2

**Comment by tlancina** [comment]
@withinsight what is the code that is failing? I wonder if there is a wrong path because apps in View are not actually located in the bundle (so things like `document://` won't work).

**Comment by amandeepmittal** [comment]
@tlancina Not working for me either. I am using **android: 7.0.0**.
@withinsight were you able to find solution?

**Comment by withinsight** [comment]
@tlancina Here's a code sample:

```
playVoiceover(currentIndex) {
    this.audio = new MediaPlugin(this.assetProvider.getAudioFullPath(this.book, this.book.pages[currentIndex]));
    this.audio.init.then(() => {}, (err) => {});
    this.audio.play({numberOfLoops: 1});
  }
```

That code sample uses a provider to build the URL, which has these functions:

```
getAudioPath (book) {
    return 'cdvfile://localhost/persistent/' + 'audio/books/' + book.imagePath + '/unit-' + book.unit + '/';
  }

  getAudioName (page) {
    return 'page-' + page.page + '.mp3';
  }

  getAudioFullPath (book, page) {
    return this.getAudioPath(book) + this.getAudioName(page);
  }
```

@amandeepmittal I did not get it working; project requirements forced us to ditch Ionic View pretty early on in favor of TestFlight and Google Play Beta testing.

**Comment by amandeepmittal** [comment]
@withinsight I tested the app on two different android devices, and it's not working. I tested the same application on iOS emulator and it works. 
@tlancina is there an alternative to get it working on an android device?

**Comment by withinsight** [comment]
@amandeepmittal To be clear, my issue was specific to Ionic View. Also, I'm using Ionic 2, so I'm using the Media Plugin of Ionic Native (which is the Ionic 2 version of ngCordova).

Using the Ionic Native Media Plugin in Ionic 2 works great on Android and iOS devices & simulators; the only issue was View.

**Comment by amandeepmittal** [comment]
@withinsight thanks for the clarification. I'd try Ionic Native Media Pluign then.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
