### ISSUE TITLE
Statusbar and Ionic view problems

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-view-issues#197]
_From @1BJK903 on November 13, 2016 21:41_

Hi there peeps,

I have some questions regarding the problems I have with the statusbar in Ionic View. First of all: everything works fine on the browser when I use Ionic Serve...

My biggest issue: the browser is not representative. Why am I saying that? Because you can't see a statusbar in the browser...

I can understand this (_cause a phone is not a desktop)_, but my actual problem starts when I am opening the application in Ionic View. There, the lay-out is not as it's in the browser, because a statusbar is being added. This adds like 10 or 20 pixels of a block where the status of the phone is being shown. This makes a mess of my nav-bar, because it overlaps it...

I tried fixing it by using this:

```
  ionic.Platform.ready(function() {
	  if (window.StatusBar) {
	    // org.apache.cordova.statusbar required
		    StatusBar.overlaysWebView(false); // or true, doesn't matter, still the same
		    StatusBar.backgroundColorByHexString('#ffffff');
	  }
	});
```

But the background color is not being applied...
Beside that, I just can't seem to fix the margin and padding issue I am having because of the statusbar...

I mean, is there a specific CSS I need to use for iOS to make it just like it is in my browser? **So to wrap it up, I have three issues:**

> 1) Statusbar not shown in the browser (this is a problem when you upload your app to Ionic View, because it is not the same anymore)
> 
> 2) The statusbar background color is not being applied
> 
> 3) Margin / Padding issue of the statusbar... how can I style it for iOS, while seeing that in my browser too? Or even hide it? Cause when I hide it, I still can see the bar... but without the text.

Can someone help me please?

_Copied from original issue: driftyco/ionic#9145_

**Comment by Thomodachi** [comment]
Hi, is there any update on this? I am facing the exactly same problem on iOS 10. Any help would be appreciated.

My cordova plugin list:
```
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-media-capture 1.4.0 "Capture"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.9.1 "PushPlugin"
```

**Comment by 1BJK903** [comment]
Nope, I am the author of the question btw. Still haven't fixed it... and Ionic isn't responding to these questions at all.

**Comment by tlancina** [comment]
Hey all, we're aware of the issue (View is undergoing a large overhaul on iOS at the moment). For a temporary workaround for the padding problem, you could try adding padding when the iOS device classes are added to `ion-app`: 
```
ion-app.platform-iphone .ion-page > ion-header > .toolbar:first-child {
  min-height: 64px;
  padding-top: 24px;
  ion-title {
    padding-top: 24px;
  }
}
```

I'm not sure the existence of those classes is documented, so I've opened an issue on the docs repo: https://github.com/driftyco/ionic-site/issues/952.

**Comment by 1BJK903** [comment]
Thanks @tlancina. When can we expect a fix / update for Ionic View?

**Comment by Thomodachi** [comment]
I accidentally managed to "resolve" this problem by changing the app name in my `config.xml`. I was forced to remove and re-add the ios platform. After building my iOS Project in XCode the statusbar showed the desired behavior.
Maybe, this helps some people.

**Comment by 1BJK903** [comment]
@Thomodachi: what else did you do? Which code did you use? Can you show us?

**Comment by Thomodachi** [comment]
I am currently using Ionic version 2.0.0-rc.3. This is what I am doing in `app.component.ts` when the platform is ready:
```
this.platform.ready().then(() => {
      StatusBar.overlaysWebView(false)
      StatusBar.backgroundColorByHexString('#000000')
    });
```

Excerpt from my `config.xml`:
```
...
<feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" />
    <param name="onload" value="true" />
</feature>
<plugin name="cordova-plugin-statusbar" spec="~2.2.0" />
...
```

After changing the app name in my `config.xml` in (in `widget.name`) I had to remove and add the ios platform. Afterwards, I build the project: 
```
cordova platform remove ios
cordova platform add ios
ionic build ios
```

In the end I use XCode to deploy the App on my iPhone or to build an archive.

**Comment by tylermakin** [comment]
This issue is duplicated in #191, #193, and #210, possibly also #35.

**Comment by EdByrnee** [comment]
Is there an ETA on when the status bar will be working within ionic view. Can't get it working within ionic 3.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
