### ISSUE TITLE
Blank screen on ionic view app

### ISSUE THREAD

**Issue by bmkopp10** [ionic-team/ionic-view-issues#200]
After updating my Cordova, installing wkwebview and installing Cordova Native Storage my app goes blank in ionic view.  It works perfectly when installed on iOS and Android.  Any ideas why this might be happening? And how I can fix it?

**Comment by OWLmx** [comment]
The same for me

**Comment by robbannn** [comment]
Got the same problem, anyone found a solution for this?

**Comment by lukeb2014** [comment]
Same problem here.

**Comment by ArthurBrito** [comment]
Same here

**Comment by bobalazek** [comment]
I have the same issue ...

**Comment by dallals** [comment]
My app worked yesterday now all I get is a grey screen

**Comment by bobalazek** [comment]
I actually figured out a few days later, that the app stops working, once you install an unsupported ionic view plugin... more information about that here: https://docs.ionic.io/tools/view/

**Comment by ahmdrz** [comment]
Same here :(

**Comment by veljkocasa** [comment]
Same here :/ working app (v1) do not work on ionic view app

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
