### ISSUE TITLE
Sharing not working properly

### ISSUE THREAD

**Issue by OWLmx** [ionic-team/ionic-view-issues#201]
When I invite someone by mail, the mail is received but when the person sign in or sign up , following the email button, with that email account, the ionic view says something like "You are logged in with an account different from the email invitation" .. I double checked the account and is exactly the same. Besides if the same email is used to sign in into the Ionic View App and the set app id directly in the preview app then I can see the app.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
