### ISSUE TITLE
Keyboard and Ionic view problems in ios

### ISSUE THREAD

**Issue by fv-david** [ionic-team/ionic-view-issues#203]
create input field in middle, the input don't autoscroll.

my code in app.component.ts
`if(this.platform.is('ios')) {
        Keyboard.disableScroll(true);
  }`

and app.module.ts
`platforms: {
    ios: {
          scrollAssist: false,
          autoFocusAssist: false
    }
 }`

my ss
![img-20170110-wa0005](https://cloud.githubusercontent.com/assets/11892197/21811627/9c1b1962-d70d-11e6-8bbc-5edbd73d9dac.jpg)

here's my ionic info.
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8
Node Version: v6.9.4
Xcode version: Not installed

respect for all answer.
sorry for my bad english.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
