### ISSUE TITLE
Ionic cloud view not reflecting in actual app installed.

### ISSUE THREAD

**Issue by Fuiste** [ionic-team/ionic-view-issues#204]
_From @shivam5x on December 24, 2016 7:40_

Hi,
  I have first installed app in ionic view and app view was acceptable and even in web acceptable, but when I installed in device its look bigger, so what is the issue when installing app in same device but difference is only that getting app in device and other one is inside the app.

In device - 
![ionic](https://cloud.githubusercontent.com/assets/16534446/21465859/37878868-c9da-11e6-8b12-15048a423b78.png)

In ionic view-
![ipa_view](https://cloud.githubusercontent.com/assets/16534446/21465861/4f1bb10c-c9da-11e6-8709-1445f9aa4a25.png)

Thanks

_Copied from original issue: driftyco/ionic-cloud-issues#253_

**Comment by Fuiste** [comment]
I'm moving this issue to the repo specifically for Ionic View issues, where it will likely get more attention.  Sorry for the confusion there!

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
