### ISSUE TITLE
Support for Google Maps

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic-view-issues#205]
It would be nice to add the [Google Maps](https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/multiple_maps) plugin so that we can use the native Google maps in Ionic View.

**Comment by Julieng50** [comment]
Google Maps seems to work for me in Ionic View, but only on the first run of my app. If I reload my app, Google Maps is not working anymore.
To make it works, 2 choices : 
 Close Ionic View then repoen it.
 Run the real Google Maps App then come back to Ionic View => my app then appears.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
