### ISSUE TITLE
Support for BackgroundGeolocation

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic-view-issues#206]
Adding the [Background Geolocation](https://github.com/mauron85/cordova-plugin-background-geolocation) plugin would be nice as well.

**Comment by MarceloEmmerich** [comment]
is there any news on this? Since I added this plugin

https://github.com/mauron85/cordova-plugin-background-geolocation

my app cannot be used from ionic view anymore. It works if installed directly on the device though.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
