### ISSUE TITLE
Ionic 2 Native Network Problem: why is it displaying an alert on the web but not on an android device? Best Regards

### ISSUE THREAD

**Issue by mainakanyi** [ionic-team/ionic-view-issues#207]
Hello, why is it displaying an alert on the web but not on an android device? Best Regards

onConnect().subscribe(() => {
console.log('network connected!');
// We just got a connection but we need to wait briefly
setTimeout(() => {
if (Network.type !== 'none') {
console.log('we got a wifi connection, woohoo!');
let alert = this.alertCtrl.create({
subTitle: 'Connection',
buttons: ['Dismiss']
});
alert.present();
}
}, 3000);
});

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
