### ISSUE TITLE
DeviceOrientation - trueHeading - null - plugin needs updating

### ISSUE THREAD

**Issue by alexbainbridge** [ionic-team/ionic-view-issues#208]
The DeviceOrientation plugin on ionic view always returns trueHeading as null when it should be set to a number between 0 and 359

magneticHeading is fine.

This is not a problem directly on device as both trueHeading AND magneticHeading return

Although I am not totally sure, I expect it is this problem which has been fixed
https://github.com/apache/cordova-plugin-device-orientation/pull/31

So I think just needs the plugin updating within Ionic View app

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
