### ISSUE TITLE
Ionic view crashes after scaning 4 barcodes and saving the data in local storage (IOS)

### ISSUE THREAD

**Issue by tlq** [ionic-team/ionic-view-issues#209]
I m facing an issue that ionic view crashes after scanning 4 barcodes and saving the data in local storage. Any ideas why its happening and how to fix it ?
Regards,
Tolga

**Comment by tlq** [comment]
I just realised that the problem actually about the camera. Ionic view only lets me to use the camera 4 times in IOS and then crushes.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
