### ISSUE TITLE
App with barcodescanner crashes on iOS when usage of camera is not allowed

### ISSUE THREAD

**Issue by luckylooke** [ionic-team/ionic-view-issues#213]
I have app which uses [this plugin](https://ionicframework.com/docs/v2/native/barcode-scanner/). Everything is OK until camera is disabled on iOS for ionic view. When this is the case, trying to open barcodescanner crashes the app to ionic view apps list and for reopen the app you need to close ionic view and reopen it, and login again into ionic view. 

I was trying lot of stuff I have found on google but nothing solved this.
I have `this.barcodeScanner.scan().then(...)` call inside try catch scope, and also did not help.

Is there a simple way I can see the error message of a crash? 

Built *.ipa - OK
Built *.apk - OK
Android Ionic View - OK
iOS Ionic View - crash!

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
