### ISSUE TITLE
ionic upload issue

### ISSUE THREAD

**Issue by musasheikh** [ionic-team/ionic-view-issues#215]
I cant find my ionic app in ionicview after uploading

would you please help!

**Comment by Luukschoen** [comment]
This is probably related: https://github.com/driftyco/ionic-cli/issues/2100

**Comment by Luukschoen** [comment]
A temporary solution would be to just downgrade the ionic-cli to v2.2 . V3beta is breaking thing atm.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
