### ISSUE TITLE
iOS camera plugin not working and index.html error

### ISSUE THREAD

**Issue by cyber227** [ionic-team/ionic-view-issues#217]
Following ionic info   for project

6.5.0
Ionic Framework Version:  1.3.2
Ionic CLI Version:  1.7.15
Ionic App Lib Version: 0.7.2
OS:  Windows 8.1
Node Version:  v4.4.5

It might be that I've overlooked a step or not deploying correctly.  This is my first Ionic App and I started before Ionic 2 was released.

In Ionic View, iOS --  I receive the following errors:

index.html       Failed to properly initialize View, please report this

Sync to Latest    ---    error copying files

If I ignore the errors above, the app works on iOS as expected until I attempt to access the camera.  Then I get

index.html      An error occurred:  plugin_not_installed

In the CLI, I added the Camera plugin to both iOS and Android deployments.  Everything on Android works -- including Camera.

For Ionic View, do I have to do a build or upload from a Mac for iOS???

Examining the code, it does appear that the plugin is listed for iOS.

**Comment by i049382** [comment]
I have the same issue as well

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
