### ISSUE TITLE
ion-img not always displaying

### ISSUE THREAD

**Issue by snortblt** [ionic-team/ionic-view-issues#218]
ion-img doesn't always load. I've used it in a virtual scroll context as well as other places with dynamically loaded containers. The images seem to load about half the time. In a situation where the image is in a template that is dynamically loaded via *ngIf, the images load initially on page load but will not display when the template is subsequently removed then re-added to the dom. This issue has been present since at least Ionic 2 RC1.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
