### ISSUE TITLE
iOS Background Services

### ISSUE THREAD

**Issue by dfliess** [ionic-team/ionic-view-issues#219]
I think that ionic View App was published without UIBackgroundModes on the plist, that's why some plugins and background services doesn't work on, for example you could 
```XML
<key>UIBackgroundModes</key>
<array>
    <string>audio</string>
</array>
```

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
