### ISSUE TITLE
View app without an account

### ISSUE THREAD

**Issue by ChristopherTotty** [ionic-team/ionic-view-issues#220]
It would be great to have the ability to view an app on a fresh install using only the appId.  

This would be useful for internal testing with multiple devices/users, sending to clients that do not want to create another account, or doing beta testing with a group of users, etc.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
