### ISSUE TITLE
"Clear all app data" does not seem to sync shared app to latest

### ISSUE THREAD

**Issue by ippeiukai** [ionic-team/ionic-view-issues#222]
I'm having problem forcing my Ionic View app to sync a shared app to latest.

Steps to reproduce:

1. [Ionic View app] sign in
1. [Ionic View app] choose "Preview a shared app"
1. [Ionic View app] type App ID and open the app
  * test the app a bit ①
1. update app with `ionic upload` ②
1. restart [Ionic View app]
1. [Ionic View app] from upper right gear icon, choose "Clear all app data"
1. [Ionic View app] choose "Preview a shared app"
1. [Ionic View app] type App ID and open the app
  * test the app a bit ③

The app shown at ③ is that of ①, not ②.

Ionic View 1.1.1, iOS 10.2.1

**Comment by pickettd** [comment]
Recently I've been having to make sure to kill the Ionic View process (restart the app) after using the Clear all app data button to make sure I can get the latest version of my app code. Not sure if you are seeing the same problem or not. But I noticed in your steps that you're restarting the Ionic View app before you are using the Clear all data option.

Here are the workaround steps I follow on my ipad:
1. Use the "Clear all app data" button
2. Double press the physical home button on the ipad
3. Swipe up on the Ionic View app to make it force quit
4. Use `ionic upload` for a new version of my code
5. Open Ionic View again on the ipad and view the app to see my latest code updates

**Comment by nikmartin** [comment]
This has become a very tough issue, as my Ionic View users are non-technical, they are end user testing the app. Trying to walk them through getting the latest version of my app loaded is brutal.

**Comment by efstathiosntonas** [comment]
Same here. I need to clear app data, kill ionic view and restart it in order to see the new app. Imagine that i've setup a loading controller when app starts with a number as a message. Before uploading i increment this number so i m always sure i m running the latest version of my app.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
