### ISSUE TITLE
Update Camera plugin to 2.3.1

### ISSUE THREAD

**Issue by dman7** [ionic-team/ionic-view-issues#223]
There is a known issue with `cordova-plugin-camera` versions 2.3.0 and below on Android 7.0 and above. When taking a picture with `$cordovaCamera` using the code:

```
$cordovaCamera.getPicture({
        saveToPhotoAlbum: false,
        quality: 50,
        allowEdit: false,
        correctOrientation: true,
        targetWidth: 750,
        targetHeight: 750,
        destinationType: Camera.DestinationType.DATA_URL,
        sourceType: Camera.PictureSourceType.CAMERA
      })
``` 

I encounter the following error:

```
"file:///storage/emulated/0/Android/data/com.ionic.viewapp/cache/.Pic.jpg exposed beyond app through ClipData.Item.getUri()"
```

This has already been raised in [Ionic Framework Forum](https://forum.ionicframework.com/t/android-7-1-google-pixel-camera-plugin-broken/71934),  answered in [ng-cordova GitHub](https://github.com/ionic-team/ng-cordova/issues/1381), and resolved in [CB-11625](https://issues.apache.org/jira/browse/CB-11625).

The fix is pretty clear: update `cordova-plugin-camera` to 2.3.1 or above (see [RELEASENOTES.md for the plugin](https://github.com/apache/cordova-plugin-camera/blob/9eba35e2f6d5c69d0594b41ac4a49cc2cfc7c3b3/RELEASENOTES.md)). 

However, as of June 12, 2017, this issue is still present as Ionic View supports only Camera 2.2.0 plugin (see [Supported Plugins](http://docs.ionic.io/tools/view/#supported-plugins)).

**Comment by saiboat** [comment]
I'm too encountering this issue and would love it to be fixed. It's tedious to test my code on my Android device at the moment because I have to rebuild the Android apk every time and I can't easily share changes with my testing buddys who are on Android >7.0

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
