### ISSUE TITLE
Ionic Sqllite Storage is not working when i build apk file 

### ISSUE THREAD

**Issue by asheeshthakur** [ionic-team/ionic-view-issues#224]
all the code working fine in the browser when i am running Ionic Serve, but when i build that same Application by using Ionic Build Android.  command then in this time Local data is not storing n sql database.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
