### ISSUE TITLE
Invitation email is not sent when sharing application

### ISSUE THREAD

**Issue by assaf13** [ionic-team/ionic-view-issues#227]
Press on share button and fill the people email. However, the mail is not sent.
I tried to share to few different people but no invitation mail was sent. Those people has ionic view account.
In the past I was able to send invitation at the same way I am trying now.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
