### ISSUE TITLE
Which libraries are supported in 'new' Ionic View

### ISSUE THREAD

**Issue by Lazarus9000** [ionic-team/ionic-view-issues#228]
I was lacking some libraries in the 'old' ionic view on iOS so I tried migrating to the 'new'. However, it seems to be even more lackluster in plugin support(?). Is there an official list of supported plugins for the 'new' Ionic view? I don't see any in the documentation.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
