### ISSUE TITLE
View is not proper in Ionic View.

### ISSUE THREAD

**Issue by GaganSuneja** [ionic-team/ionic-view-issues#229]
Ionic view has issues in mi phones . App Does not show font properly aligned

![screenshot_2017-08-30-10-29-07-522_com ionic viewapp](https://user-images.githubusercontent.com/9746527/29856233-149431ea-8d6f-11e7-9fd4-ee746d2d0dc8.png)

![screenshot_2017-08-30-10-29-35-244_com ionic viewapp](https://user-images.githubusercontent.com/9746527/29856220-048e1cb6-8d6f-11e7-9036-f1fa13ff2405.png)

Device info
Screen 720*1280
xiomi redmi 2 
density unit 320
density type
xhdpi

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
