### ISSUE TITLE
Ionic View - SVGs not working 

### ISSUE THREAD

**Issue by kensodemann** [ionic-team/ionic-view-issues#231]
_From @Kapsul-Brice on September 12, 2017 19:12_

**Ionic version:**  
[ ] **1.x** 
[ ] **2.x**
[X ] **3.x**

**I'm submitting a ...**  
[X ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
The SVG images are visible on devices (both android+ios) / working fine on devices and emulators
The SVG images are hidden in Ionic View / Not working in Ionic View

**Expected behavior:**
The SVG images should be visible / working in Ionic View

**Steps to reproduce:**
Push an app with SVGs <img> to ionic pro backend
Open this app in Ionic View

**Related code:**

```
<img src="assets/images/home_btn_1.svg"  />
```

**Other information:**
Forum link : https://forum.ionicframework.com/t/svg-file-is-not-shown-on-ionic-view/105063

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 
    Gulp CLI    : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    Node              : v6.11.2
    npm               : 5.4.1 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
```

_Copied from original issue: ionic-team/ionic#12870_

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This appears to be an issue with Ionic View and not the Ionic Framework, so I am going to move this issue to `ionic-team/ionic-view-issues`. Please follow the item over there.

Thank you for using Ionic

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
