### ISSUE TITLE
is not a function errors when trying to view app

### ISSUE THREAD

**Issue by enthusiasmus** [ionic-team/ionic-view-issues#232]
I downloaded the latest "Ionic View" App from the Google Play Store, but I can't connect to my app stored at ionic. Following errors occur: 

When clicking on *VIEW APP*:
![screenshot_20170917-224249](https://user-images.githubusercontent.com/1102208/30524770-ed481978-9bf9-11e7-9880-e9a342daae98.png)

When going back to the app overview:
![screenshot_20170917-224253](https://user-images.githubusercontent.com/1102208/30524769-ed4539ba-9bf9-11e7-9f56-c20de4ddf307.png)

Seems to me as two bugs? Any thoughts?
best regards

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
