### ISSUE TITLE
Ionic-view detection

### ISSUE THREAD

**Issue by sergeychernyshev** [ionic-team/ionic-view-issues#29]
Until all the plugins are there, I might need to vary the functionality of my app when it's loaded in Ionic-Viewer (open external browser instead of inAppBrowser, for example).

Please provide a way to detect the fact that app is being previewed in "Ionic-View" so I can tweak the behavior for previewers.

**Comment by tlancina** [comment]
Hey this is a great idea, did you have anything in mind? I was thinking of setting a variable as early as possible on window so that any code you run could check if it's running in View.

**Comment by keithdmoore** [comment]
@tlancina I was thinking of ionic.Platform.isIonicView() but I see that there may be some value to putting in on window.

**Comment by sebestenyb** [comment]
I'm not sure it would solve @keithdmoore's issue.

Regarding the CORS issue:
* in local browser using proxy you need an api url with localhost
* on a real device no matter if in Ionic View or the production app, you need the real API url.

Detecting Ionic View won't help with this, you (or rather w) need to figure out if we are on a real device or testing with `ionic serve`.

**Comment by crissi** [comment]
if you want to check if running on device you can use this: (document.location.protocol == "file:")

Maybe ionic needs an isDevice() function?

**Comment by sebestenyb** [comment]
Thanks, I've ended up the same solution, but it still would be nice having something like that next to all the different ```is*()``` detection methods in Ionic. ```isDevice()``` sounds logical :)

**Comment by dopry** [comment]
+1 I'm current using isWebView on Android to determine if my app is running in ionicView. I'd like to see isWebView() also return true on iOS.  if that isn't a feasible way to overload isWebView, a new is* Flag would be nice.

In an ideal world  from ionic.Platform I could easily distinguish

1. App running a browser (ionic serve)
2. App running in Ionic View
3. Native App running for debugging (ionic run)
4. Native App installed from store.

**Comment by alejandromagnorsky** [comment]
+1

**Comment by jason-engage** [comment]
Any progress here? Is there a solution? +1

**Comment by keithdmoore** [comment]
I assume this will be needed for the Ionic Deploy service as well, right?

**Comment by tlancina** [comment]
Try checking for the key ionicView in Localstorage, kind of a temporary workaround until there is a robust way of doing it.

**Comment by jason-engage** [comment]
I threw in ngStorage, and did a JSON.stringify alert on $localStorage, the object was empty. Does it get inserted at a specific time?

**Comment by dopry** [comment]
I experienced the same. I didn't see anything in the chrome remote debugger.

On Thu, Jun 25, 2015 at 1:44 PM, jason-engage <notifications@github.com>
wrote:

> I threw in ngStorage, and did a JSON.stringify alert on $localStorage, the
> object was empty. Does it get inserted at a specific time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/29#issuecomment-115342063>
> .
>



-- 
Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Comment by tlancina** [comment]
Ah it may not be in Android yet, if that's what you guys are using.

I wonder if you could check window.location.href on Android, since a normal
index.html would be in file:///android_asset/, but in View it would be in
something like file:///data/data/. I haven't tried it, but it might be
worth a shot.

**Comment by rozaydin** [comment]
+1 
window.location.href is indeed different 
on ionic view 
file:///data/data/com.ionic.viewapp/files/files/<ionicappid>/index.html
on Android 
file:///android_asset/www/index.html
however it would be better to have sth like ionic.Platform.isIonicView()

**Comment by JLNNN** [comment]
+1

**Comment by VinceOPS** [comment]
+1

**Comment by rajeshwarpatlolla** [comment]
+1

**Comment by nikhilenmudi** [comment]
+1

**Comment by bboldi** [comment]
+1

**Comment by eduardonunesp** [comment]
+1

**Comment by nebrekab** [comment]
+1

**Comment by sergeychernyshev** [comment]
I gave up on Ionic Viewer as most of my apps require plugin integrations so I had to build them and created good enough pipeline. Might need this again when I prototype my next app.

**Comment by devandy** [comment]
+1

**Comment by lotterfriends** [comment]
I use this function as a temporary workaround 
https://gist.github.com/lotterfriends/53395722b063caafa5c2e34031c6a25c
+1 for a ionic solution

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
