### ISSUE TITLE
View App Does Not Obey Orientation Preference On Android

### ISSUE THREAD

**Issue by saniyusuf** [ionic-team/ionic-view-issues#42]
I have my app on the Ionic view on android. The app seems to rotate when I rotate the screen but the previously built version is installed on my app and  does not rotate. Also on IOS in the view app it does not rotate but does on Android which leads me to believe it is an issue affecting only android.

**Comment by simplesmiler** [comment]
Ionic View did not support landscape orientation prior to 1.0.6.

Related to https://github.com/driftyco/ionic-view-issues/issues/55

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
