### ISSUE TITLE
Facebook login not working in Ionic view

### ISSUE THREAD

**Issue by qnodesign** [ionic-team/ionic-view-issues#45]
At least for me..

in Simulator it works perfectly, but in the ionic-view app it is showing the following message:

`The redirect_uri URL is not supported.`

I was using this guide for the integration: https://github.com/ccoenraets/OpenFB

and it seems the given "Valid OAuth redirect URI" -s (localhost for the local development and https://www.facebook.com/connect/login_success.html as a Valid OAuth redirect URI for access from Cordova) are working fine on the emulator and on the local browser as well. Only the ionic view app drops this message, most probably because the URI. Is there a solution for this?

**Comment by chingchia** [comment]
Having the same problem. Still looking for solutions

**Comment by toregua** [comment]
Exactly the same problem for me using hellojs.  Need a solution too please

**Comment by chingchia** [comment]
@toregua 
After a few days of trial-and-error, I finally have a solution for the Facebook log-in/ log-out problem for Ionic. 
It is actually a fixed version of the old OpenFB library.
The sample app can log-in/out correctly on all platforms(browser, iOS, and Android).
Please check this repo:
https://github.com/chingchia/sociogram-angular-ionic

Some comments are here:
http://forum.ionicframework.com/t/facebook-clean-log-out-and-log-in-with-a-different-user/20613

**Comment by toregua** [comment]
@chingchia Thank you very much for your answer. In fact I have just tried to use http://localhost:8100/ URL (like explain in your repo) in facebook developer and it works for me :)

**Comment by AnthonyTsang** [comment]
Same here, I am using ng-cordova-oauth and it works on emulator and APK but some issues on ionic-view. 
Android: nothing happened after login
iOS: error showing in facebook page "The page you requested cannot be displayed right now..."

**Comment by verdi327** [comment]
+1 I'm using ng-cordova-oauth with firebase.  Works on emulator and device, but just freezes on Fbook login screen after I hit 'Log In'.  I've added the above mentioned urls to my facebook app.  Still no dice.

**Comment by elhamsarikhani** [comment]
+1 same here. my screen frozes in iOS, using ionic view, as I click on login.

**Comment by pfallasro** [comment]
I'm also struggling with this issue, I am able to login using Parse's facebook login but can't make it work in Ionic view, basically the authentication screen never shows up.

**Comment by elhamsarikhani** [comment]
guys as it turned out, inAppBrowser plugin is not supported in ionic view. that's what's missing and causing this issue.

**Comment by marcelor** [comment]
elhamsarikhani, any idea about when will inAppBrowser be supported?

**Comment by pfallasro** [comment]
I don't think so, I gave up on Parse's facebook login and started using the cordovaoAuth plugin and it's working like a charm in ionic view the downside is that it only works on a phone.

**Comment by elhamsarikhani** [comment]
This is official list of plugins supported by ionic view:
http://docs.ionic.io/docs/view-usage
As you can see, inAppBrowser is not in the list.
please vote for this plugin to be added in here: https://github.com/driftyco/ionic-view-issues/issues/15

**Comment by simplesmiler** [comment]
@pfallasro are you talking about [ng-cordova-oauth](https://github.com/nraboy/ng-cordova-oauth)? How did you make it work in ionic view?

**Comment by qkrrlwp** [comment]
what should i do..

**Comment by IvanLisz** [comment]
+1

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
