### ISSUE TITLE
Local Image doesn't display 

### ISSUE THREAD

**Issue by joseSantacruz** [ionic-team/ionic-view-issues#54]
When i use image on the project folder and upload to ionic view the image doesn't display.

**Comment by judecoster** [comment]
Same problem here :-)

**Comment by expleosoftware** [comment]
And here... src or ng-src on image tag does not show the image, but url('xxx') in css seems to be working.

**Comment by amirkheirabadi** [comment]
for me too....

**Comment by BipinBhandari** [comment]
Same here..please fix it soon

**Comment by dannypule** [comment]
I'm getting the same issue. Images show up as broken image in ionic view. I'm using ng-src

**Comment by improvi** [comment]
Same issue here... using ng-src...

**Comment by ClintonVanSciver** [comment]
Issue for me too. I'm using standard img-src and while no image is displayed, there's no broken image icon.

**Comment by salehrastani** [comment]
same here, but im encountering the problem for the marker image on the map options in google maps api:    
    var image = {
      url: "../img/motor-bike-64.png"
    }
So im basically doing javascript but Ionic view wont show the marker image? Thanks!

**Comment by Cyruxx** [comment]
+1

**Comment by maketroli** [comment]
I NEED IT FIXED. Come on, in another issue I address this same problem around 2 or 3 months ago.

**Comment by mateeyow** [comment]
+1 I'm surprised it this is a month old problem and ionic 1.0.0 was already launched.

**Comment by tlancina** [comment]
Are the images in www?

**Comment by mateeyow** [comment]
Yes, inside the img folder. When serving the app using `ionic serve` there were no problems. But when running it using `ionic run --device` the images cannot be rendered.

**Comment by maketroli** [comment]
@tlancina www ? what do you mean ? like external URL ? no, actually my problem is with local images, with the images I have in a folder within the project.

**Comment by simplesmiler** [comment]
`/img/image.png` did not work for me, but `img/image.png` did. Hope this helps.

**Comment by dvlasenko96** [comment]
I has this problem too. What should i do?

**Comment by mateeyow** [comment]
I figured mine out by using the link `img/<image_file>`, also the image should be inside `www/img` folder. My only blunder was adding **$locationProvider** on my config file.

**Comment by liulixiang1988** [comment]
Same issue here. When serving the app using `ionic serve` there were no problems. But when running it using `ionic run --device` the images cannot be rendered. The  images are from web.

**Comment by maciejpawlowski** [comment]
Try remove the leading '/'. Worked for me

**Comment by dvlasenko96** [comment]
Thank. I removed '/' , and everything works.

**Comment by bsiddiqui** [comment]
:+1: to removing '/'

**Comment by salehrastani** [comment]
It worked for me as well. I had to remove the starting "../"  and now it
finds the image file. Yaaaay!

**Comment by wilguevara** [comment]
+1 @simplesmiler that works fine for me to!

**Comment by kamaroly** [comment]
I have removed / too on both the $http.get('/services.json') and on all images and it worked like charm 
@simplesmiler thanks

**Comment by afsalcodehack** [comment]
use src="img/logo.png" instead of src="../img/logo.png"

**Comment by thehiddennepali** [comment]
I am getting images from my remote server and I am providing full image path of the server but still don't work

**Comment by wellborn** [comment]
What is your image path?
Are you using the image path like http://www.sitename.com/images/abc.jpg?
.... it should be like this

**Comment by akmalazlanjamal** [comment]
Remove '/' seems to do the trick. But in WebStorm IDE did detect it as a 'cannot resolve file'. That does not really matter as long as it works.

**Comment by Cyruxx** [comment]
@akmalazlanjamal WebStorm tries to resolve the path correctly, but it just can't. That's totally fine, just ignore it.

**Comment by omt66** [comment]
As  mateeyow said already, instead of ../img/<image-name> just use img/<image-name>, i.e. remove the '..' when using the local images from the www dir.

**Comment by isipro** [comment]
It does not work for me in Ionic View (works in browser testing) 
when I am using "../img/*.jpg " to go one level up 
( having the .html file in www/templates and the .jpg in www/img )
Fixed by removing the "../" - works on both places now

**Comment by gebidesign** [comment]
+1 for removing '../'
``` html
<!--before-->
<img src="../img/logo.svg" alt="Logo">

<!--after-->
<img src="img/logo.svg" alt="Logo">
```

**Comment by Goundar** [comment]
+ 1 for removing '../'

**Comment by vpego** [comment]
+1 for removing "../", 

please let us know if this is going to change someday..

**Comment by zahidul-alam-m4** [comment]
same here.

**Comment by Frogmarch** [comment]
+1 for ./img/xxx.png

**Comment by ronyrun** [comment]
Anyone know how to manage the onerror ?

onerror="this.src='img/logo.png'" it doesn't work.

**Comment by doctorwebbrasil** [comment]
+1 here too ... works without "../" perfect

**Comment by jamesngondo2013** [comment]
I had the same problem when I created an apk file...no images. All I has to do was remove the / in front of img. I now had img/name_of_image.jpg.

**Comment by jatinlucky** [comment]
My code is working after removed '../img/' from the path. Thanks

**Comment by hkboujrida** [comment]
removing the '/' was not working for me so i was wondering why the ionic.png works in the demo app and when i add my image in the img folders it doesnt work
So the solution is to alter this file  :<your project>/platforms/android/build/intermediates/incremental/mergeAssets/debug/merger.xml

add to this section your image :

`<dataSet config="main">
<source path="<yp>\platforms\android\assets">
<file name="www/img/ionic.png" path="<yp>\platforms\android\assets\www\img\ionic.png"/>      
<file name="www/img/myimage.png" path="<yp>\platforms\android\assets\www\img\myimage.png"/>`

Hope this helps
flies away ...

**Comment by MohamedSaber19** [comment]
removing ../ works for me thanks guys (y)

**Comment by ohnu93** [comment]
I've tried adding `<allow-navigation href="*" />
  <allow-navigation href="file://*/*" />` to my `config.xml` upon seeing the news of > android 4.4 having issues with pulling up images but still no luck.

I'm testing this on Samsung Galaxy 4 with android api level 21 (android 5.0.1).
I get following error for my `<img src="img/live.png">``:
`Failed to load resource: net::ERR_FILE_NOT_FOUND file:///android_asset/www/img/live.png`
And using the chrome inspect function, I see that there are no "img" folder that lives inside my `file:///android_asset/www` folder. But in my `app_root_directory/platforms/android/assets/www` folder, "img" folder is there with my `live.png` inside it.

PLEASE fix it :(

**Comment by maciejpawlowski** [comment]
try <img src="**/**img/live.png">

**Comment by ohnu93** [comment]
@maciejpawlowski  still no luck ;( it still gives the same error but now it's trying to find images from a strange location now: `file:///img/live.png`. I am expecting my device to find the images that lay inside `android_asset/www/img` folder? Am I not? I mean I placed my images in `www/img` folder...

**Comment by SanjayYadav90** [comment]
Image not being display in background why?
I have same issue,
I try for removing that / and ../
but it wont work for me.
here is what i did-
```
in view-
<ion-content class="padding login">
in css-
.login {
    background: url(/img/mainmenubackground.jpg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
}
```
Help me if anyone can!!!

**Comment by SanjayYadav90** [comment]
Hi all,
After doing much googling i got my issue resolved,

see what i did as-
in view-

`<ion-view view-title="Dashboard" class="login">`
in css- 
`.login {
    background: url(../img/mainmenubackground.jpg) no-repeat center center; 
    -webkit-background-size: 100%;
    -moz-background-size: 100%;
}`
in img-
`image is located here
/img/mainmenubackground.jpg
`
this [link](http://stackoverflow.com/questions/29660016/ionic-background-image-not-showing-on-device) help me a lot...

I also write for my blog here as-
https://randvblog.wordpress.com/2016/06/17/issue-background-image-doesnt-display-in-device-on-ionic/

**Comment by ohnu93** [comment]
Unlike @SanjayYadav90 's success, I've been trying to load my images as icons via css class in my `ion-tabs` which I have "temporarily resolved" by saving my images in my `firebase` storage and loading images `ion-tabs` icons from there.

Before taking this "temporary" measures to resolve this issue, I've come to a conclusion that this is happening because `ion-tabs` icons do get loaded before my asset files get loaded into the device, hence the `Failed to load resource: net::ERR_FILE_NOT_FOUND`. Anyone experiencing the same issue?

**Comment by j-francisco** [comment]
I switched from "/img/abc.png" to "img/abc.png" and it still wasn't working in Ionic View, even though it worked fine with ionic serve and the emulator. The solution for me was to click "Clear App Data" in the Ionic View app, then the image started appearing.

**Comment by luispestanajr** [comment]
In my specific case, the problem was the --livereload param from CLI.

I do not know if it will help you, but try to run your project without --livereload.

Hope can help you or someone else!

**Comment by mahendrarajdhami** [comment]
just removing ../  works
`<img src="img/ionic.png">`

**Comment by amity203** [comment]
My old images are showing but my newly added images are not displaying in ionic view app, in browser there is not problem, it is something that we need to make some different amount to bind img folder again with the build? Why anyone from Ionic team is responding with a official solution?

**Comment by matheusmpessoa** [comment]
+1 to remove ../

**Comment by robindierckx** [comment]
Doesn't work with absolute path on android:
<div class="sizing cover" ng-repeat="pic in ProjectCtrl.getProjectPictures()" cache-src="https://creo2-s3-bucket.s3.amazonaws.com/media/projects/India-4-min-min.png" src-is="background" >
 </div>

However it works on browser testing with ionic serve

**Comment by sasanom** [comment]
<img src={{ ... }}> didn't work
<img ng-src={{ ... }}> worked

**Comment by hubbubca** [comment]
+1 to remove leading /

**Comment by iursevla** [comment]
I'm facing this problem too. Is there a workaround?

**Comment by hubbubca** [comment]
Remove the leading /.  '/img/whatever.png' becomes 'img/whatever.png' etc.

**Comment by khullah** [comment]
Didn't worked:
- removing "/" and "../"
- using ng-src
- neither <img> or in css
- I'm not using --livereload
- and I'm not using Ionic View app

Then all of a sudden, all did work! What changed? Not sure, actually.... bummer
But do note this:

- the magic _appeared_ to happen when I watched case-sensitive file extension (PNG, not png, as that file)
- In CSS, worked only with '../', and in html without it (using ng-src, which seems better case the app loads before the assets, and angular would update when available)
- Sources in chrome inspect still doesn't show the img folder.

**Comment by adibas03** [comment]
remove preceeding ` ../ `  from the image url

**Comment by pritish5** [comment]
try this
https://github.com/peteygao/MediaScannerPlugin

**Comment by khullah** [comment]
@pritish5  can you elaborate on that?

**Comment by omarfouad** [comment]
I had the same issue, then I realized I should have used relative paths instead of absolute ones.

Hope this helps.

**Comment by eaktadiur** [comment]
Hi,
I had same issue. I was try to load image form "file:///storage/sdcard/0/ExampleProject/test.png" <img ng-src="file:///storage/sdcard/0/ExampleProject/test.png"/>. i was using chrome://inspect to debug the device. I was getting an error "Not allowed to load local resource: file:///storage/sdcard/0/ExampleProject/test.png". 

I fixed it just add one line code in index.html
<meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src  'self' 'unsafe-inline' *; img-src 'self' data: *">

and make sure u build and deploy in ur device. chrome://inspect will not work

thanks

**Comment by joshgarwood** [comment]
@eaktadiur can you tell us what line of code you added to make it work?  Thanks!

**Comment by eaktadiur** [comment]
pls check my repo https://github.com/eaktadiur/ionic-file-Browser @joshgarwood 
let me know is there any issue

**Comment by joshgarwood** [comment]
THanks so much!

**Comment by Atta-Ur-Rehman** [comment]
Create a img Directory in your src Directory and insert all images in directory and also copy img folder and  put it into www folder then image will show ...  Issue fixed :+1:

**Comment by Oliviez** [comment]
That's quite tricky but thanks simplesmiler !

**Comment by jluisfg** [comment]
Removing "../" worked for me also :)

**Comment by alejandrofransoy** [comment]
Hi, in my case the image was not shown in a device and yes in the browser. The motif ended up being the dimensions of the image, it was very large. I reduced them and showed them correctly

**Comment by yathishc** [comment]
Simple Solution

Old with error :::::
<img src="../../assets/icon/sm-con.png" class="sm-icon"/>

Error Free Code 

<img src="assets/icon/sm-con.png" class="sm-icon"/>


This Works for Both desktop view and Mobile view

**Comment by AlGantori** [comment]
What is working for me both when running off the local ionic serve or from the content of www copied to my web host is to use relative notation
../assets/img/<your-image>
like so

    .AMSView-background {
      background: url(../assets/img/UMSViewBGTile.png)  center center fixed;
      background-size: 50px;
      background-repeat: repeat;
    
    }

I just did a ionic run android --prod
and the above relative specification **fixed the issue** as well on Android.

I have never built for iOS so I can't comment there.

Note: the above ../assets/img/ is working from my .scss files which I believe are getting compiled into build/main.css, thus it explains why we have to go up one parent.

However, my reference from html which from my observation also gets transpiled into main.js using 

    ../assets/img

but forcing current folder like so 

    ./assets/img 

as in

        <button ion-button (click)="AMSController.Loop()"> <img src="./assets/img/PC_LOOP.png" width="30px" height="30px"/> </button>
    </div>

works in 2 areas, on local ionic serve and anywhere installed on my web host.  I can't explain why it works.

However it does not work on Android.

Perhaps someone can show me how to convert the image nested above inside an ion-button into a spec from a .css so that I can take advantage of the '../assets/img/" path specification which is already working in 3 cases

 1. Local 
 2. Hosted on my web folder 
 3. Android


**UPDATE: I have a fix for Android as well**.

 1. Using nothing as in "assets/img/PC_Loop.png"
 2. Pay attention to your filename and extension case PC_Loop.png and not PC_LOOP.png in my case.  I happen to host on Windows which does not care (case-INSENSITIVE), but Android is a stupid Unix machine.  So on Unix hosting you probably also observe issues with casing.

I dislike very much anything case-sensitive, including all sensitive languages and programmers :), but I like case aware environments (language, OS, ...)

**SUMMARY:**
So why use nothing (current folder) from .HTML and "../" from .CSS files when I think of both being at the same level is totally absurd.

Hope this helps the next person.

**Comment by sgadekar81** [comment]
if you are using <img>
then use ->  <img src="assets/images/lifetime.png" class="logo">


if you are using css
then use->
background:url('../assets/images/empty-timeline-bg-1.jpg');

**Comment by khullah** [comment]
You're right @sgadekar81, matches my observations above as well.

**Comment by nottinhill** [comment]
Any version of this image declaration path game fails with karma and the demo by the ionic team. @ionic team: Please resolve.

**Comment by dgaurav** [comment]
yes it will work via src="assets/images/avtar.png" in mobile build but it's not show on browser. it should be fixed from ionic end.

**Comment by joancolmenerodev** [comment]
@simplesmiler +1 worked like a charm! 🥇

**Comment by peterprice** [comment]
Before using the suggested path format (src="assets/images/avtar.png") would work for me, I had to delete and recreate the app at https://apps.ionic.io/apps/ and update the app_id in ionic.config.json.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
