### ISSUE TITLE
bug: Can't type in ionic view

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-view-issues#58]
_From @FranklinWaller on March 24, 2015 11:59_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>When you try to type with a view on this setup: http://codepen.io/anon/pen/NPobgz You have to type character by character. While this works without the ionic view.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3389_

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
