### ISSUE TITLE
loginworkflow for facebook does not work in ionic view app

### ISSUE THREAD

**Issue by pharindoko** [ionic-team/ionic-view-issues#61]
Hey,

I used this sample in the ionic view app
https://github.com/nraboy/ng-cordova-facebook-example
and another sample using angular azure mobile services with fb login

For both I receive I receive a white screen of death after successful log in in facebook 

Does this happen due to missing support for in app browser plugin at the current moment ?

**Comment by tlancina** [comment]
Yeah I believe that's correct, I haven't tried Facebook, but I'm pretty
sure oauth uses inAppBrowser in part of its authentication, which fails
because the plugin isn't supported yet.

**Comment by piclez** [comment]
Hi tlancina, any idea or ETA how to add this plugin support?!

**Comment by quanghoc** [comment]
Firebase Ionic social login doesn't work either. Having inAppBrowser inside a inAppBrowser is tricky, isn't it? ;-)

**Comment by adamelevate** [comment]
+1
I love the app, truly a big help... but this one thing is needs some tlc  :)

**Comment by jason-engage** [comment]
@tlancina is there any workout to get the authentication to work within Ionic View? We could wrap a case statement for the login code depending on whether its loading within Ionic View or not...

**Comment by andrhahn** [comment]
+1  
I'm also stuck on this one.  It's not just specific to the ionic-view app, it also doesnt work in ios simulator.

Any workarounds?  As of now this feature is unusable.

**Comment by elhamsarikhani** [comment]
+1
most of the apps need authentication and adding the support for inAppBrowser plugin would really be a big help.

**Comment by diegopso** [comment]
+1
Any news about this?

**Comment by chris-barnett** [comment]
+1 any updates? Still receiving white screen

**Comment by golear91** [comment]
This seems like one of the most used Plugins, is there any reason why you guys still haven't added support for it in Ionic View?

**Comment by tlancina** [comment]
Hey all, this is on our radar as probably the #1 requested feature (aka InAppBrowser support). It's a little tricky because View itself is a custom InAppBrowser, but there's no reason supporting it shouldn't be possible.

**Comment by goleary** [comment]
Happy to hear it's on your radar, and hoping we see support soon.  I love the idea of Ionic view but it's unusable without this plugin.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
