### ISSUE TITLE
Document supported platforms

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionic-view-issues#63]
On http://view.ionic.io/, document which plugins are supported.

**Comment by kgmiller** [comment]
Such a list would be very helpful. I've been getting a blank screen for my app in Ionic View since integrating the ngCordova SQLite plugin.

**Comment by LanceEa** [comment]
You can find the supported plug-ins here. 
http://docs.ionic.io/tools/viewapp/

**Comment by cfjedimaster** [comment]
But you don't see that here: http://view.ionic.io/

There needs to be a direct link to those docs imo for easy discovery.

On Wed, Apr 1, 2015 at 1:05 PM, Lance Austin <notifications@github.com>
wrote:

> You can find the supported plug-ins here.
> http://docs.ionic.io/tools/viewapp/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/63#issuecomment-88578890>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by LanceEa** [comment]
I agree that it needs to be easier to find. It took me awhile to find it so I wanted to at least share it with people until we hear back from the Ionic Team.

**Comment by simplesmiler** [comment]
List of supported plugins has been moved here: http://docs.ionic.io/docs/view-usage

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
