### ISSUE TITLE
Cannot delete decommissioned app from Ionic View

### ISSUE THREAD

**Issue by whazzmaster** [ionic-team/ionic-view-issues#69]
We had a restart of a project where it had one app id, and then we wiped it and started with a new app id. I had previously used `ionic upload` to play with the first iteration on my Galaxy S5, and now I have two instances of the same app showing in both in the web interface at [apps.ionic.io](http://apps.ionic.io) as well as in the Ionic View app on the phone.

When I go to delete the old version of the app via the phone, however, it asks for confirmation and then displays:

![ionic-view-delete-error](https://cloud.githubusercontent.com/assets/102357/6971185/519187c2-d940-11e4-9054-dcd59f1e1a36.png)

I'd love to be able to clear out the entry for the old app.

**Comment by tlancina** [comment]
Are you the owner of the app or was it shared with you?

**Comment by sebestenyb** [comment]
We had the same issue, I've shared the app with my colleague, and later deleted it.
Now the app stuck in her account, she can't remove it.
So to clarify, you are not able to remove a shared app from your account, if the original author already deleted it from his.

**Comment by tlancina** [comment]
Thanks @sebestenyb that definitely sounds like a bug! We're looking into it.

**Comment by jspenc72** [comment]
Had the same problem

**Comment by jspenc72** [comment]
I looks as tho I am now able to delete an app however people I have shared the ID with can still download it as a shared app after it is decommissioned. The expected behavior if you don't want to delete the information from your server would be to mark the app as deleted by me and do not allow others to download it with an error message saying something like, "App has been deleted by the creator"

**Comment by jspenc72** [comment]
https://github.com/driftyco/ionic-view-issues/issues/95

**Comment by devidas7** [comment]
Hello, I am getting the confirmation of project deletion, but the confirmation box has no any button like "ok" or "Cancel", its just a popup message

**Comment by izwanmansor** [comment]
same problem here with @devidas7 ... **only pop up message**

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
