### ISSUE TITLE
PopUp "Delete App" on Ionic View not showing the buttons to eliminate projects .

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionic-view-issues#81]
When I want delete a proyect in Ionic View, the PopUp is not show buttons for delete proyect and on the web site does not allow delete them.

Proyect ID dfa03b20

**Comment by tlancina** [comment]
Android or iOS?

**Comment by Judavaro** [comment]
Andriod Tim

2015-04-24 12:25 GMT-05:00 Tim Lancina <notifications@github.com>:

> Android or iOS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/81#issuecomment-96002682>
> .
>



-- 
Coridialmente,

Juan David Vanegas Romero
Técnico en programación de sistemas de información
PSP Fundamentals
ISTQB Fundamentals
3013506792

**Comment by EuPaulo** [comment]
Had the same problem on Android.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
