### ISSUE TITLE
Invalid invite

### ISSUE THREAD

**Issue by sebestenyb** [ionic-team/ionic-view-issues#92]
Using `ionic share ...` results invalid invites frequently.
I've shared an app with **7** people, and at least **2** of them couldn't follow the invite link, as it was invalid.
(It's not following the same invites twice, or trying to follow it after a long time, it displayed invalid the same day.)

Found a we similar tickets:
https://github.com/driftyco/ionic-cli/issues/312
https://github.com/driftyco/ionic-cli/issues/307

**Comment by alejandromagnorsky** [comment]
+1. This is a big issue since it's the main goal of Ionic View.

**Comment by sirhoe** [comment]
++1 
it happens to my invite too.

**Comment by larpo1** [comment]
same problem here

**Comment by leob** [comment]
This happened to me too. Generally this means that you (or the user) isn't logged in with a valid "ionic.io" user account. When you get this error message, there are generally 2 tiny links (which are easy to miss) at the top of the page: "signup" and "login". Use them to create an ionic.io account or log in with an existing one. When the user does that they end up in the ionic.io pag of your app and will still have no clue what to do. They then need to install and open the Ionic View app and log in there (with the same account) and then they will be able to view your app. Not the most intuitive user experience imaginable.

**Comment by jpike88** [comment]
still nothing... are you guys serious???

**Comment by leob** [comment]
The "invite" feature with the email isn't critical at all. Once the (test) user installs the Ionic View app and logs in with a user name and password that you provide to them then they can view and test all your uploaded apps without a problem. The 'invite' feature isn't much more than a nice gimmick.

**Comment by jpike88** [comment]
You may consider it a "gimmick", but the primary reason anyone even sends invites is to get others to use Ionic View. The invites fail miserably on that level, and not just at being valid links, but at actually indicating that the app is available on Ionic View.

For any users who aren't already clued in in advance by myself, or have the patience to investigate things, it's a pain in the ass. So no, I'd consider it a critical usability issue.

**Comment by alejandromagnorsky** [comment]
Still having problems with the invite functionality. Also the process should be simpler for the invitee.

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
